/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nouf
 */
public class FeedbackM extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackM
     */
    public FeedbackM() {
        initComponents();
        Sqlconnector();
        loadReviewsIntoTable();
        setupFilter();
    }

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(FeedbackM.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(FeedbackM.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reviews = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        backBR = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reviews.setBackground(new java.awt.Color(204, 204, 204));
        Reviews.setForeground(new java.awt.Color(0, 0, 0));
        Reviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer ID", "Product Name", "Rating", "Review", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Reviews.setGridColor(new java.awt.Color(0, 0, 0));
        Reviews.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Reviews.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Reviews.setShowGrid(true);
        Reviews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReviewsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReviewsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Reviews);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, 890, 440));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Feedbacks");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("X");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });
        jPanel1.add(backBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 930, 20));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Status");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        status.setBackground(new java.awt.Color(0, 0, 0));
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checked", "Under review" }));
        status.setBorder(null);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 30));

        jLabel10.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Search");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 20));

        Search.setBackground(new java.awt.Color(0, 0, 0));
        Search.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setSelectionColor(new java.awt.Color(51, 153, 255));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 930, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
        new ManagerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
    
        // Add ActionListener to the status combo box
        status.addActionListener(e -> {
    // Check if a row is selected in the Reviews table
    int selectedRow = Reviews.getSelectedRow();
    if (selectedRow != -1) { // Ensure a row is selected
        try {
            // Get the selected review ID (primary key) from the table
            String reviewID = Reviews.getValueAt(selectedRow, 0).toString(); // Assuming column 0 is Review ID

            // Get the selected status from the combo box
            String selectedStatus = status.getSelectedItem().toString();

            // Prevent redundant updates (if the status is unchanged)
            String currentStatus = Reviews.getValueAt(selectedRow, 5).toString(); // Assuming column 4 is the status
            if (currentStatus.equals(selectedStatus)) {
                return; // Do nothing if the status is the same
            }

            // Prepare the SQL query to update the status
            String updateQuery = "UPDATE productreview SET status = ? WHERE ID = ?";

            // Create a PreparedStatement and set the parameters
            PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
            updateStmt.setString(1, selectedStatus); // Set the status value
            updateStmt.setString(2, reviewID); // Set the Review ID

            // Execute the update
            int rowsAffected = updateStmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Status updated successfully.");

                // Update the status in the table directly
                Reviews.setValueAt(selectedStatus, selectedRow, 5); // Update column 4 in the table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update status.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error updating status: " + ex.getMessage());
            ex.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a review record to update the status.");
    }
});
    }//GEN-LAST:event_statusMouseClicked

    private void ReviewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReviewsMouseClicked

        Reviews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = Reviews.getSelectedRow();
        
        if (selectedRow != -1) {
            // Fetch the current status from the selected row
            String currentStatus = Reviews.getValueAt(selectedRow, 5).toString(); // Assuming column 5 is the status
            status.setSelectedItem(currentStatus); // Update combo box to match current status
        }
    }
});
    }//GEN-LAST:event_ReviewsMouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
 
    }//GEN-LAST:event_statusActionPerformed

    private void ReviewsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReviewsMousePressed
       
    }//GEN-LAST:event_ReviewsMousePressed

    private void loadReviewsIntoTable() {
    try {
        // SQL query to fetch all reviews from the productreview table
        String query = "SELECT ID, Customer_userID, product_name, rate, review, status FROM productreview";

        // Prepare and execute the query
        PreparedStatement St = Con.prepareStatement(query);
        ResultSet rst = St.executeQuery();

        // Get metadata for column count
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();

        // Get the table model for the Reviews table
        DefaultTableModel d = (DefaultTableModel) Reviews.getModel();

        // Clear the table before adding rows
        d.setRowCount(0);

        // Iterate through the result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();

            // Add each column value to the vector (match column order in the query)
            vc.add(rst.getInt("ID"));             // Auto-generated review ID
            vc.add(rst.getString("Customer_userID"));    // Customer ID
            vc.add(rst.getString("product_name")); // Product name
            vc.add(rst.getInt("rate"));           // Rating
            vc.add(rst.getString("review"));      // Review
            vc.add(rst.getString("status"));      // Status (can be null)

            // Add the row to the table model
            d.addRow(vc);
        }

        // Refresh the table display
        Reviews.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(FeedbackM.class.getName()).log(Level.SEVERE, null, ex);
    }
}

  private void filter(String query) {
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>((DefaultTableModel) Reviews.getModel());
    Reviews.setRowSorter(tr);

    // Apply the regex filter to the "user_name" column (index 1)
    tr.setRowFilter(RowFilter.regexFilter(query, 1));  // Change the index for different columns
}

  private void setupFilter() {
    // Assuming Search is the JTextField where the user types to filter
    Search.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            String query = Search.getText();  // Get text from the text field
            filter(query);  // Apply the filter to the table
        }
    });
}
    
    private void Clear() {
    status.setSelectedIndex(0);
    Search.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Reviews;
    private javax.swing.JTextField Search;
    private javax.swing.JButton backBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
