/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nouf
 */
public class InvManageM extends javax.swing.JFrame {

    /**
     * Creates new form InvManageM
     */
    public InvManageM() {
        initComponents();
        Sqlconnector();
        loadProdIntoTable();
        setupFilter();
        loadIngMIntoTable();
        setupFilter2();
        
    }

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabPanel = new javax.swing.JTabbedPane();
        Products = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodTableM = new javax.swing.JTable();
        InvID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InvName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Search1 = new javax.swing.JTextField();
        addM = new javax.swing.JButton();
        DelUM = new javax.swing.JButton();
        UpUM = new javax.swing.JButton();
        clearUM = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        InvS = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        InvP = new javax.swing.JTextField();
        InvCat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Ingredients = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingTableM = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        quantity = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        stockIng = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Search2 = new javax.swing.JTextField();
        addM1 = new javax.swing.JButton();
        DelUM1 = new javax.swing.JButton();
        UpUM1 = new javax.swing.JButton();
        clearUM1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        backBR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        prodM = new javax.swing.JButton();
        ingM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TabPanel.setBackground(new java.awt.Color(255, 255, 255));

        Products.setBackground(new java.awt.Color(255, 255, 255));
        Products.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodTableM.setAutoCreateRowSorter(true);
        prodTableM.setBackground(new java.awt.Color(204, 204, 204));
        prodTableM.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        prodTableM.setForeground(new java.awt.Color(0, 0, 0));
        prodTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Stock", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prodTableM.setGridColor(new java.awt.Color(0, 0, 0));
        prodTableM.setSelectionBackground(new java.awt.Color(0, 0, 0));
        prodTableM.setSelectionForeground(new java.awt.Color(255, 255, 255));
        prodTableM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prodTableM.setShowGrid(true);
        prodTableM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodTableMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodTableM);
        if (prodTableM.getColumnModel().getColumnCount() > 0) {
            prodTableM.getColumnModel().getColumn(0).setPreferredWidth(40);
            prodTableM.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        Products.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, 450));

        InvID.setBackground(new java.awt.Color(204, 204, 204));
        InvID.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        InvID.setForeground(new java.awt.Color(0, 0, 0));
        InvID.setText(" ");
        Products.add(InvID, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 130, -1));
        InvID.getAccessibleContext().setAccessibleName(" ");

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID");
        Products.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Category");
        Products.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");
        Products.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        InvName.setBackground(new java.awt.Color(204, 204, 204));
        InvName.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        InvName.setForeground(new java.awt.Color(0, 0, 0));
        InvName.setText(" ");
        Products.add(InvName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 130, -1));
        InvName.getAccessibleContext().setAccessibleName(" ");

        jLabel10.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Search");
        Products.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 70, 20));

        Search1.setBackground(new java.awt.Color(0, 0, 0));
        Search1.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        Search1.setForeground(new java.awt.Color(255, 255, 255));
        Search1.setSelectionColor(new java.awt.Color(51, 153, 255));
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        Products.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 160, -1));

        addM.setBackground(new java.awt.Color(0, 153, 255));
        addM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addM.setForeground(new java.awt.Color(255, 255, 255));
        addM.setText("ADD");
        addM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMMouseClicked(evt);
            }
        });
        Products.add(addM, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 80, 30));

        DelUM.setBackground(new java.awt.Color(0, 153, 255));
        DelUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        DelUM.setForeground(new java.awt.Color(255, 255, 255));
        DelUM.setText("DELETE");
        DelUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelUMMouseClicked(evt);
            }
        });
        Products.add(DelUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 80, 30));

        UpUM.setBackground(new java.awt.Color(0, 153, 255));
        UpUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        UpUM.setForeground(new java.awt.Color(255, 255, 255));
        UpUM.setText("UPDATE");
        UpUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpUMMouseClicked(evt);
            }
        });
        UpUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpUMActionPerformed(evt);
            }
        });
        Products.add(UpUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 80, 30));

        clearUM.setBackground(new java.awt.Color(0, 153, 255));
        clearUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearUM.setForeground(new java.awt.Color(255, 255, 255));
        clearUM.setText("CLEAR");
        clearUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearUMMouseClicked(evt);
            }
        });
        Products.add(clearUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 80, 30));

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Stock");
        Products.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        InvS.setBackground(new java.awt.Color(204, 204, 204));
        InvS.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        InvS.setForeground(new java.awt.Color(0, 0, 0));
        InvS.setText(" ");
        Products.add(InvS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 130, -1));

        jLabel17.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Price (RM)");
        Products.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        InvP.setBackground(new java.awt.Color(204, 204, 204));
        InvP.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        InvP.setForeground(new java.awt.Color(0, 0, 0));
        InvP.setText(" ");
        Products.add(InvP, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 130, -1));

        InvCat.setBackground(new java.awt.Color(204, 204, 204));
        InvCat.setFont(new java.awt.Font("Footlight MT Light", 0, 14)); // NOI18N
        InvCat.setForeground(new java.awt.Color(0, 0, 0));
        InvCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cookies", "Pies", "Cakes", "Breads", "Pasteries" }));
        InvCat.setBorder(null);
        InvCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvCatActionPerformed(evt);
            }
        });
        Products.add(InvCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 130, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Products");
        Products.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        TabPanel.addTab("", Products);

        Ingredients.setBackground(new java.awt.Color(255, 255, 255));
        Ingredients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingTableM.setBackground(new java.awt.Color(204, 204, 204));
        ingTableM.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        ingTableM.setForeground(new java.awt.Color(0, 0, 0));
        ingTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Stock", "Cost (Per Unit)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ingTableM.setSelectionBackground(new java.awt.Color(0, 0, 0));
        ingTableM.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ingTableM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingTableMMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ingTableM);

        Ingredients.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 41, 520, 450));

        jLabel13.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID");
        Ingredients.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        id.setBackground(new java.awt.Color(204, 204, 204));
        id.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 0));
        Ingredients.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        jLabel14.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Name");
        Ingredients.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        name.setBackground(new java.awt.Color(204, 204, 204));
        name.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        Ingredients.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jLabel15.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Quantity");
        Ingredients.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        quantity.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        quantity.setBorder(null);
        Ingredients.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, 30));

        jLabel16.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Stock");
        Ingredients.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        stockIng.setBackground(new java.awt.Color(204, 204, 204));
        stockIng.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        stockIng.setForeground(new java.awt.Color(0, 0, 0));
        stockIng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Full" }));
        stockIng.setBorder(null);
        Ingredients.add(stockIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 160, 30));

        jLabel9.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Search");
        Ingredients.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        Search2.setBackground(new java.awt.Color(0, 0, 0));
        Search2.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        Search2.setForeground(new java.awt.Color(255, 255, 255));
        Search2.setSelectionColor(new java.awt.Color(51, 153, 255));
        Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search2ActionPerformed(evt);
            }
        });
        Ingredients.add(Search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 170, -1));

        addM1.setBackground(new java.awt.Color(0, 153, 255));
        addM1.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        addM1.setForeground(new java.awt.Color(255, 255, 255));
        addM1.setText("ADD");
        addM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addM1MouseClicked(evt);
            }
        });
        Ingredients.add(addM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 80, -1));

        DelUM1.setBackground(new java.awt.Color(0, 153, 255));
        DelUM1.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        DelUM1.setForeground(new java.awt.Color(255, 255, 255));
        DelUM1.setText("DELETE");
        DelUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelUM1MouseClicked(evt);
            }
        });
        Ingredients.add(DelUM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        UpUM1.setBackground(new java.awt.Color(0, 153, 255));
        UpUM1.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        UpUM1.setForeground(new java.awt.Color(255, 255, 255));
        UpUM1.setText("UPDATE");
        UpUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpUM1MouseClicked(evt);
            }
        });
        UpUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpUM1ActionPerformed(evt);
            }
        });
        Ingredients.add(UpUM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        clearUM1.setBackground(new java.awt.Color(0, 153, 255));
        clearUM1.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        clearUM1.setForeground(new java.awt.Color(255, 255, 255));
        clearUM1.setText("CLEAR");
        clearUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearUM1MouseClicked(evt);
            }
        });
        Ingredients.add(clearUM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Ingredients");
        Ingredients.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Cost");
        Ingredients.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        cost.setBackground(new java.awt.Color(204, 204, 204));
        cost.setFont(new java.awt.Font("Footlight MT Light", 1, 14)); // NOI18N
        Ingredients.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, 30));

        TabPanel.addTab("", Ingredients);

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("X");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Inventory Management");

        prodM.setBackground(new java.awt.Color(0, 153, 255));
        prodM.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        prodM.setForeground(new java.awt.Color(255, 255, 255));
        prodM.setText("Products");
        prodM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodMMouseClicked(evt);
            }
        });

        ingM.setBackground(new java.awt.Color(0, 153, 255));
        ingM.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        ingM.setForeground(new java.awt.Color(255, 255, 255));
        ingM.setText("Ingredients");
        ingM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanel)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prodM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingM)
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodM)
                        .addComponent(ingM)
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 940, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
        new ManagerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void prodMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodMMouseClicked
        TabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_prodMMouseClicked

    private void ingMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingMMouseClicked
        TabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_ingMMouseClicked

    private void Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search2ActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void addMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMMouseClicked

        if (InvName.getText().isEmpty() || InvS.getText().isEmpty() || InvP.getText().isEmpty() ) {
    JOptionPane.showMessageDialog(this, "Missing Information");
} else {
    try {
        int stock = 0;
        double price = 0.0;

        try {
            stock = Integer.parseInt(InvS.getText());  
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid stock value. Please enter a valid integer.");
            return;  
        }

        try {
            price = Double.parseDouble(InvP.getText()); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price value. Please enter a valid number.");
            return;  
        }

        String query = "INSERT INTO Products (product_name, category, quantity, price) VALUES (?, ?, ?, ?)";
        PreparedStatement addStmt = Con.prepareStatement(query);

        String productName = InvName.getText();  
        String category = InvCat.getSelectedItem().toString();  

        addStmt.setString(1, productName);  
        addStmt.setString(2, category);  
        addStmt.setInt(3, stock);  
        addStmt.setDouble(4, price);  

        int row = addStmt.executeUpdate();

        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Product Record Saved!");
            loadProdIntoTable(); 
            Clear(); 
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save product record.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_addMMouseClicked

    private void DelUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelUMMouseClicked

         if (InvID.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Product ID is missing.");
        } else {
    String productID = InvID.getText().trim();  // Get the input from the user
    String query = "DELETE FROM Products WHERE product_id = ?";  

    try (PreparedStatement stmt = Con.prepareStatement(query)) {
       
        stmt.setInt(1, Integer.parseInt(productID));

        String checkQuery = "SELECT product_id FROM Products WHERE product_id = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setInt(1, Integer.parseInt(productID));
        ResultSet checkResult = checkStmt.executeQuery();

        if (!checkResult.next()) {
           
            JOptionPane.showMessageDialog(this, "No Product Record Found with ID: " + productID);
        } else {
           
            int result = stmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Product Record Deleted!");
                loadProdIntoTable();  
                Clear(); 
            } else {
                JOptionPane.showMessageDialog(this, "Delete operation failed.");
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
        Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid format for Product ID");
    }
}

    }//GEN-LAST:event_DelUMMouseClicked

    private void UpUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpUMMouseClicked

        if (InvID.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Product ID is missing.");
} else {
    try {
        int productID = Integer.parseInt(InvID.getText());
        String productName = InvName.getText();  
        String category = InvCat.getSelectedItem().toString();  
        int stock = Integer.parseInt(InvS.getText());  
        double price = Double.parseDouble(InvP.getText());  

        // Check if the product exists
        String checkQuery = "SELECT product_id FROM Products WHERE product_id = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setInt(1, productID);
        ResultSet checkResult = checkStmt.executeQuery();

        if (!checkResult.next()) {
            JOptionPane.showMessageDialog(this, "Product not found.");
        } else {
            // Update query without recipe ID, production date, expiry date, and batch number
            String updateQuery = "UPDATE Products SET product_name = ?, category = ?, quantity = ?, price = ? WHERE product_id = ?";

            PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
            updateStmt.setString(1, productName);  
            updateStmt.setString(2, category);  
            updateStmt.setInt(3, stock);  
            updateStmt.setDouble(4, price);  
            updateStmt.setInt(5, productID);  

            int result = updateStmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Product details updated successfully!");
                loadProdIntoTable();  // Refresh the product table
                Clear();  // Clear input fields
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input for product ID, stock, or price.");
    }
}


    }//GEN-LAST:event_UpUMMouseClicked

    private void UpUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpUMActionPerformed

    private void clearUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearUMMouseClicked
        Clear();
    }//GEN-LAST:event_clearUMMouseClicked

    private void addM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addM1MouseClicked

       if (name.getText().isEmpty() || quantity.getValue() == null || cost.getText().isEmpty()|| stockIng.getSelectedIndex() == -1) {
    JOptionPane.showMessageDialog(this, "Missing Information");
       } else {
    try {
        // Proceed with the insert (no need to check for ingredient_id)
        String query = "INSERT INTO Ingredients (ingredient_name, ingredient_quantity, stock_status, Cost_perunit) VALUES (?, ?, ?, ?)";
        PreparedStatement addStmt = Con.prepareStatement(query);
        
        // Set values for the insert statement
        addStmt.setString(1, name.getText());  // Ingredient Name
        addStmt.setInt(2, (Integer) quantity.getValue());  // JSpinner value for Ingredient Quantity
        addStmt.setString(3, stockIng.getSelectedItem().toString());  // Ingredient Status
        addStmt.setDouble(4, Double.parseDouble(cost.getText().toString()));

        // Execute the insert query
        int row = addStmt.executeUpdate();
        
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient Saved!");
            loadIngMIntoTable();  // Refresh the table
            Clear2();  // Clear the input fields
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in Ingredient Quantity.");
    }
}

    }//GEN-LAST:event_addM1MouseClicked

    private void DelUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelUM1MouseClicked

        if (id.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Information is Missing");
        } else {
    String ingredientID = id.getText().trim();
    String query = "DELETE FROM Ingredients WHERE ingredient_id = ?";  

    try (PreparedStatement stmt = Con.prepareStatement(query)) {
        // Convert the Ingredient ID from String to Integer
        stmt.setInt(1, Integer.parseInt(ingredientID));

        // Execute the delete operation
        int result = stmt.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient Deleted!");
            loadIngMIntoTable();  // Refresh the table after deletion
            Clear2();  // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "No Ingredient Found with ID: " + ingredientID);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
        Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid format for Ingredient ID");
    }
}
    }//GEN-LAST:event_DelUM1MouseClicked

    private void UpUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpUM1MouseClicked

        DefaultTableModel model2 = (DefaultTableModel) ingTableM.getModel();
        int selectedRow = ingTableM.getSelectedRow();
        if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select an Ingredient to edit.");
    return;
        }

try {
    // Retrieve and validate input fields
    String ingredientIdText = id.getText().trim();
    String ingredientName = name.getText().trim(); // JTextField for Ingredient Name
    String ingredientStatus = stockIng.getSelectedItem() != null ? stockIng.getSelectedItem().toString() : ""; // JComboBox for Status
    String costText = cost.getText().trim(); // JTextField for Cost

    if (ingredientIdText.isEmpty() || ingredientName.isEmpty() || ingredientStatus.isEmpty() || costText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please ensure all fields are filled correctly.");
        return;
    }

    // Parse numeric fields and validate
    int ingredientID = Integer.parseInt(ingredientIdText); // Ingredient ID
    int ingredientQuantity = ((Number) quantity.getValue()).intValue(); // Get value from JSpinner
    double ingredientCost = Double.parseDouble(costText); // Cost from JTextField

    // SQL update query
    String query = "UPDATE Ingredients SET ingredient_name = ?, ingredient_quantity = ?, Stock_Status = ?, Cost_perunit = ? WHERE ingredient_id = ?";

    // Execute the query
    try (PreparedStatement st = Con.prepareStatement(query)) {
        st.setString(1, ingredientName);
        st.setInt(2, ingredientQuantity);
        st.setString(3, ingredientStatus);
        st.setDouble(4, ingredientCost);
        st.setInt(5, ingredientID);

        int result = st.executeUpdate(); // Perform the update

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient updated successfully.");
            loadIngMIntoTable(); // Refresh the table after the update
            Clear2(); // Clear the input fields after the update
        } else {
            JOptionPane.showMessageDialog(this, "No ingredient found with ID: " + ingredientID + ", update failed.");
        }
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Invalid number format in Ingredient ID, Quantity, or Cost fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database access error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_UpUM1MouseClicked

    private void UpUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpUM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpUM1ActionPerformed

    private void clearUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearUM1MouseClicked
        Clear2();
    }//GEN-LAST:event_clearUM1MouseClicked

    private void InvCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvCatActionPerformed
        
    }//GEN-LAST:event_InvCatActionPerformed

    private void prodTableMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodTableMMouseClicked
        DefaultTableModel model = (DefaultTableModel) prodTableM.getModel();  
        int selectedRow = prodTableM.getSelectedRow(); 
        if (selectedRow != -1) {  
            InvID.setText(model.getValueAt(selectedRow, 0).toString());         
            InvName.setText(model.getValueAt(selectedRow, 1).toString());      
            InvCat.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
            InvS.setText(model.getValueAt(selectedRow, 3).toString());      
            InvP.setText(model.getValueAt(selectedRow, 4).toString());           
        } else {
            JOptionPane.showMessageDialog(this, "Please select a product record to edit.");
       }

    }//GEN-LAST:event_prodTableMMouseClicked

    private void ingTableMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingTableMMouseClicked
      DefaultTableModel model2 = (DefaultTableModel) ingTableM.getModel();
        int MyIndex = ingTableM.getSelectedRow();
        id.setText(model2.getValueAt(MyIndex, 0).toString());
        name.setText(model2.getValueAt(MyIndex, 1).toString());
        quantity.setValue(Integer.parseInt(model2.getValueAt(MyIndex, 2).toString())); 
        stockIng.setSelectedItem(model2.getValueAt(MyIndex, 3).toString());
    }//GEN-LAST:event_ingTableMMouseClicked

     private void loadProdIntoTable() {
    try {
    String query = "SELECT * FROM products"; 

    St = Con.prepareStatement(query);
    rst = St.executeQuery();

    // Get metadata for column count
    java.sql.ResultSetMetaData Rsd = rst.getMetaData();
    int c = Rsd.getColumnCount();

    // Get the table model for the product table
    DefaultTableModel d = (DefaultTableModel) prodTableM.getModel(); 

    // Clear the table before adding rows
    d.setRowCount(0);

    while (rst.next()) {
        Vector vc = new Vector();

        // Add each column value to the vector (match column order)
        vc.add(rst.getInt("product_id"));
        vc.add(rst.getString("product_name"));
        vc.add(rst.getString("category"));
        vc.add(rst.getInt("quantity"));
        vc.add(rst.getDouble("price"));  // Assuming price is a double

        // Add the row to the table model
        d.addRow(vc);
    }

    // Refresh the table display
    prodTableM.repaint(); // Assuming 'ProductTableM' is your table model name

} catch (SQLException ex) {
    Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, null, ex);
}
     }

  private void filter(String query) {
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>((DefaultTableModel) prodTableM.getModel());
    prodTableM.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query, 1)); 
}

  private void setupFilter() {
    
    Search1.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            String query = Search1.getText();  
            filter(query);  
        }
    });
}
    
    private void Clear() {
    InvID.setText("");
    InvName.setText("");
    InvCat.setSelectedIndex(0);
    InvS.setText("");
    InvP.setText("");
    cost.setText("");
    Search1.setText("");
}
    
    private void loadIngMIntoTable() {
    try {
        // SQL query to join Products and Recipes tables using product_name
        String query = "SELECT * from ingredients";
        
        // Prepare the statement and execute the query
        St = Con.prepareStatement(query);
        rst = St.executeQuery();
        
        // Get the metadata of the result set
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();
        
        // Get the DefaultTableModel of the JTable
        DefaultTableModel d = (DefaultTableModel) ingTableM.getModel();
        
        // Clear existing rows before adding new ones
        d.setRowCount(0);
        
        // Iterate through the result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();
            
            // Add each column value to the vector (match column order)
            vc.add(rst.getString("ingredient_id")); 
            vc.add(rst.getString("ingredient_name"));
            vc.add(rst.getInt("ingredient_quantity")); 
            vc.add(rst.getString("Stock_Status")); 
            vc.add(rst.getDouble("Cost_perunit")); 
            // Add the vector as a row in the table
            d.addRow(vc);
        }

        // Repaint the table to make sure it's updated
        ingTableM.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(InvManageM.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void filter2(String query) {
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>((DefaultTableModel) ingTableM.getModel());
    ingTableM.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter("(?i)" + query, 1)); 
}


  private void setupFilter2() {
    Search2.addKeyListener(new KeyAdapter() {
        public void keyReleased(KeyEvent e) {
            String query = Search2.getText();  
            filter2(query);  // Correct method call
        }
    });
}

    
    private void Clear2() {
    id.setText("");
    name.setText("");
    quantity.setValue(0);
    stockIng.setSelectedIndex(0);
    Search2.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvManageM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelUM;
    private javax.swing.JButton DelUM1;
    private javax.swing.JPanel Ingredients;
    private javax.swing.JComboBox<String> InvCat;
    private javax.swing.JTextField InvID;
    private javax.swing.JTextField InvName;
    private javax.swing.JTextField InvP;
    private javax.swing.JTextField InvS;
    private javax.swing.JPanel Products;
    private javax.swing.JTextField Search1;
    private javax.swing.JTextField Search2;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JButton UpUM;
    private javax.swing.JButton UpUM1;
    private javax.swing.JButton addM;
    private javax.swing.JButton addM1;
    private javax.swing.JButton backBR;
    private javax.swing.JButton clearUM;
    private javax.swing.JButton clearUM1;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField id;
    private javax.swing.JButton ingM;
    private javax.swing.JTable ingTableM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JButton prodM;
    private javax.swing.JTable prodTableM;
    private javax.swing.JSpinner quantity;
    private javax.swing.JComboBox<String> stockIng;
    // End of variables declaration//GEN-END:variables
}
