/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;
import bakerymanagementsystem.Login;
/**
 *
 * @author Nouf
 */
public class ManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ManagerDashboard
     */
    public ManagerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sep = new javax.swing.JPanel();
        UserM = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        OrderM = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        FinM = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        InvM = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        LogoutM = new javax.swing.JLabel();
        FeedM = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 645));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sep.setBackground(new java.awt.Color(255, 255, 255));
        sep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sepMouseClicked(evt);
            }
        });

        UserM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        UserM.setForeground(new java.awt.Color(0, 0, 0));
        UserM.setText("Users");
        UserM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        OrderM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        OrderM.setForeground(new java.awt.Color(0, 0, 0));
        OrderM.setText("Orders");
        OrderM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderMMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        FinM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        FinM.setForeground(new java.awt.Color(0, 0, 0));
        FinM.setText("Finance");
        FinM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinMMouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        InvM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        InvM.setForeground(new java.awt.Color(0, 0, 0));
        InvM.setText("Inventory");
        InvM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvMMouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LogoutM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        LogoutM.setForeground(new java.awt.Color(0, 0, 0));
        LogoutM.setText("Logout");
        LogoutM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMMouseClicked(evt);
            }
        });

        FeedM.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        FeedM.setForeground(new java.awt.Color(0, 0, 0));
        FeedM.setText("Feedback");
        FeedM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedMMouseClicked(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout sepLayout = new javax.swing.GroupLayout(sep);
        sep.setLayout(sepLayout);
        sepLayout.setHorizontalGroup(
            sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(UserM)
                .addGap(49, 49, 49)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(OrderM)
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(FinM)
                .addGap(44, 44, 44)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(InvM)
                .addGap(46, 46, 46)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(FeedM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(LogoutM)
                .addGap(41, 41, 41))
        );
        sepLayout.setVerticalGroup(
            sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FeedM)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvM)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinM)
                    .addGroup(sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LogoutM)
                        .addGroup(sepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(OrderM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 950, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome-11-22-2024 (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 990, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rb_66573 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMMouseClicked

        new UserManageM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserMMouseClicked

    private void OrderMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderMMouseClicked
        new OrderManageM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrderMMouseClicked

    private void FinMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinMMouseClicked
        new FinanceManageM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FinMMouseClicked

    private void InvMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvMMouseClicked
        new InvManageM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InvMMouseClicked

    private void LogoutMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMMouseClicked

    private void FeedMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedMMouseClicked
        new FeedbackM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FeedMMouseClicked

    private void sepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sepMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sepMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FeedM;
    private javax.swing.JLabel FinM;
    private javax.swing.JLabel InvM;
    private javax.swing.JLabel LogoutM;
    private javax.swing.JLabel OrderM;
    private javax.swing.JLabel UserM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel sep;
    // End of variables declaration//GEN-END:variables
}
