/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manager;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Nouf
 */
public class UserManageM extends javax.swing.JFrame {

    /**
     * Creates new form UserManageM
     */
    public UserManageM() {
        initComponents();
        Sqlconnector();
        loadUsersIntoTable();
        setupFilter();
    }

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(UserManageM.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(UserManageM.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTableM = new javax.swing.JTable();
        DelUM = new javax.swing.JButton();
        UpUM = new javax.swing.JButton();
        clearUM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userNameM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passM = new javax.swing.JTextField();
        Search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userIDM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        roleM = new javax.swing.JComboBox<>();
        addM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("X");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("User Management");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        UserTableM.setAutoCreateRowSorter(true);
        UserTableM.setBackground(new java.awt.Color(204, 204, 204));
        UserTableM.setForeground(new java.awt.Color(0, 0, 0));
        UserTableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "Password", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        UserTableM.setGridColor(new java.awt.Color(0, 0, 0));
        UserTableM.setSelectionBackground(new java.awt.Color(0, 0, 0));
        UserTableM.setShowGrid(true);
        UserTableM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTableM);

        DelUM.setBackground(new java.awt.Color(0, 153, 255));
        DelUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        DelUM.setForeground(new java.awt.Color(255, 255, 255));
        DelUM.setText("DELETE");
        DelUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelUMMouseClicked(evt);
            }
        });

        UpUM.setBackground(new java.awt.Color(0, 153, 255));
        UpUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        UpUM.setForeground(new java.awt.Color(255, 255, 255));
        UpUM.setText("UPDATE");
        UpUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpUMMouseClicked(evt);
            }
        });
        UpUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpUMActionPerformed(evt);
            }
        });

        clearUM.setBackground(new java.awt.Color(0, 153, 255));
        clearUM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearUM.setForeground(new java.awt.Color(255, 255, 255));
        clearUM.setText("CLEAR");
        clearUM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearUMMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User Name ");

        userNameM.setBackground(new java.awt.Color(204, 204, 204));
        userNameM.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        userNameM.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Role");

        passM.setBackground(new java.awt.Color(204, 204, 204));
        passM.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        passM.setForeground(new java.awt.Color(0, 0, 0));

        Search.setBackground(new java.awt.Color(0, 0, 0));
        Search.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setSelectionColor(new java.awt.Color(51, 153, 255));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Search");

        jLabel7.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("User ID ");

        userIDM.setBackground(new java.awt.Color(204, 204, 204));
        userIDM.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        userIDM.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password");

        roleM.setBackground(new java.awt.Color(204, 204, 204));
        roleM.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        roleM.setForeground(new java.awt.Color(0, 0, 0));
        roleM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Baker" }));
        roleM.setBorder(null);

        addM.setBackground(new java.awt.Color(0, 153, 255));
        addM.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addM.setForeground(new java.awt.Color(255, 255, 255));
        addM.setText("ADD");
        addM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(343, 343, 343)
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(Search)
                                                .addGap(12, 12, 12))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(userIDM, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(userNameM, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(passM, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roleM, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(addM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clearUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DelUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UpUM)))
                                .addGap(51, 51, 51)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userIDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(roleM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DelUM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpUM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearUM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 940, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DelUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelUMMouseClicked
    
        if (userIDM.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "User ID is missing.");
} else {
    String userID = userIDM.getText().trim();  // Get the input from the user
    String query = "DELETE FROM users WHERE user_id = ?";  // SQL query for deletion

    try (PreparedStatement stmt = Con.prepareStatement(query)) {
        // Convert the User ID from String to Integer
        stmt.setInt(1, Integer.parseInt(userID));

        // Check if the user exists in the database
        String checkQuery = "SELECT user_id FROM users WHERE user_id = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setInt(1, Integer.parseInt(userID));
        ResultSet checkResult = checkStmt.executeQuery();

        if (!checkResult.next()) {
            // If the user does not exist, show an error message
            JOptionPane.showMessageDialog(this, "No User Record Found with ID: " + userID);
        } else {
            // If the user exists, execute the delete operation
            int result = stmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "User Record Deleted!");
                loadUsersIntoTable();  
                Clear();  
            } else {
                JOptionPane.showMessageDialog(this, "Delete operation failed.");
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
        Logger.getLogger(UserManageM.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid format for User ID");
    }
}
    }//GEN-LAST:event_DelUMMouseClicked

    private void UpUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpUMMouseClicked

        if (userIDM.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "User ID is missing.");
} else {
    try {
        int userID = Integer.parseInt(userIDM.getText());  // Parse the user ID from the text field
        String userName = userNameM.getText();  // Get the user name from the text field
        String userPassword = passM.getText();  // Get the user password from the text field
        String userRole = roleM.getSelectedItem().toString();  // Get the selected role from the JComboBox

        // First, check if the user exists in the database
        String checkQuery = "SELECT user_id FROM Users WHERE user_id = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setInt(1, userID);
        ResultSet checkResult = checkStmt.executeQuery();

        // If no user with this ID exists, show an error message
        if (!checkResult.next()) {
            JOptionPane.showMessageDialog(this, "User not found.");
        } else {
            // User exists, proceed with the update

            // Prepare the SQL query to update the user name, user password, and user role
            String updateQuery = "UPDATE Users SET user_name = ?, user_password = ?, role_name = ? WHERE user_id = ?";

            // Prepare the statement and set the parameters
            PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
            updateStmt.setString(1, userName);  // Set the new user name
            updateStmt.setString(2, userPassword);  // Set the new user password
            updateStmt.setString(3, userRole);  // Set the new user role
            updateStmt.setInt(4, userID);  // Set the user ID

            // Execute the update query
            int result = updateStmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "User details updated successfully!");
                loadUsersIntoTable();  // Refresh the table with the updated data
                Clear();  // Clear the input fields
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input for User ID.");
    }
}


    }//GEN-LAST:event_UpUMMouseClicked

    private void UpUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpUMActionPerformed

    private void clearUMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearUMMouseClicked
        Clear();
    }//GEN-LAST:event_clearUMMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void UserTableMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMMouseClicked
        
       DefaultTableModel model = (DefaultTableModel) UserTableM.getModel();  // Get the table's model
       int selectedRow = UserTableM.getSelectedRow();  // Get the selected row index
       if (selectedRow != -1) {  // Check if a row is selected
    // Set the values in the fields from the selected row
    userIDM.setText(model.getValueAt(selectedRow, 0).toString()); 
    userNameM.setText(model.getValueAt(selectedRow, 1).toString()); 
    passM.setText(model.getValueAt(selectedRow, 2).toString());  
    String selectedRole = model.getValueAt(selectedRow, 3).toString();  
    roleM.setSelectedItem(selectedRole);  
       } else {
    JOptionPane.showMessageDialog(this, "Please select a user record to edit.");
       }

    }//GEN-LAST:event_UserTableMMouseClicked

    private void addMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMMouseClicked

        // Check if any required fields are empty
if (userNameM.getText().isEmpty() || passM.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Missing Information");
} else {
    try {
        // Proceed with inserting into Users table (no need to provide user_id as it's auto-increment)
        String query = "INSERT INTO Users (user_name, user_password, role_name) VALUES (?, ?, ?)";

        PreparedStatement addStmt = Con.prepareStatement(query);

        // Get values for the insert statement
        String userName = userNameM.getText();  // User Name
        String userPassword = passM.getText();  // User Password
        String userRole = roleM.getSelectedItem().toString();  // Get the selected role from the JComboBox

        // Set values for the insert statement
        addStmt.setString(1, userName);  // User Name
        addStmt.setString(2, userPassword);  // User Password
        addStmt.setString(3, userRole);  // User Role

        // Execute the insert query
        int row = addStmt.executeUpdate();

        if (row > 0) {
            JOptionPane.showMessageDialog(this, "User Record Saved!");
            loadUsersIntoTable();  // Refresh the table with updated data
            Clear();  // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save user record.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in fields.");
    }
}

    }//GEN-LAST:event_addMMouseClicked

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
        new ManagerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

   private void loadUsersIntoTable() {
    try {
        String query = "SELECT u.user_id, u.user_name, u.user_password, u.role_name " +
               "FROM Users u " +
               "JOIN Roles r ON u.role_name = r.role_name";


        St = Con.prepareStatement(query);
        rst = St.executeQuery();

        // Get metadata for column count
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();

        // Get the table model for the users table
        DefaultTableModel d = (DefaultTableModel) UserTableM.getModel();

        // Clear the table before adding rows
        d.setRowCount(0);

        while (rst.next()) {
            Vector vc = new Vector();

            // Add each column value to the vector (match column order)
            vc.add(rst.getInt("user_id"));  
            vc.add(rst.getString("user_name"));  
            vc.add(rst.getString("user_password"));  
            vc.add(rst.getString("role_name"));  // Fetch role_name from Roles table  
              

            // Add the row to the table model
            d.addRow(vc);
        }

        // Refresh the table display
        UserTableM.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(UserManageM.class.getName()).log(Level.SEVERE, null, ex);
    }
}

  private void filter(String query) {
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>((DefaultTableModel) UserTableM.getModel());
    UserTableM.setRowSorter(tr);

    // Apply the regex filter to the "user_name" column (index 1)
    tr.setRowFilter(RowFilter.regexFilter(query, 1));  // Change the index for different columns
}

  private void setupFilter() {
    // Assuming Search is the JTextField where the user types to filter
    Search.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            String query = Search.getText();  // Get text from the text field
            filter(query);  // Apply the filter to the table
        }
    });
}
    
    private void Clear() {
    userIDM.setText("");
    userNameM.setText("");
    passM.setText("");
    roleM.setSelectedIndex(0);
    Search.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManageM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManageM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelUM;
    private javax.swing.JTextField Search;
    private javax.swing.JButton UpUM;
    private javax.swing.JTable UserTableM;
    private javax.swing.JButton addM;
    private javax.swing.JButton backBR;
    private javax.swing.JButton clearUM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField passM;
    private javax.swing.JComboBox<String> roleM;
    private javax.swing.JTextField userIDM;
    private javax.swing.JTextField userNameM;
    // End of variables declaration//GEN-END:variables
}
