/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baker;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.Date;

/**
 *
 * @author Nouf
 */
public class EquipManageB extends javax.swing.JFrame {

    /**
     * Creates new form EquipManageB
     */
    public EquipManageB() {
        initComponents();
        Sqlconnector();
        loadEquipIntoTable();
    }

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EquipManageB.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(EquipManageB.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipTableBR = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        equipIDBR = new javax.swing.JTextField();
        equipNameBR = new javax.swing.JTextField();
        equipStatusBR = new javax.swing.JComboBox<>();
        updateBR = new javax.swing.JButton();
        deleteBR = new javax.swing.JButton();
        clearBR = new javax.swing.JButton();
        addBR = new javax.swing.JButton();
        backBR = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 96, 79));
        jLabel1.setText("Equipment Management");

        equipTableBR.setBackground(new java.awt.Color(115, 96, 79));
        equipTableBR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipment ID", "Equipment Name", "Equipment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipTableBR.setGridColor(new java.awt.Color(0, 0, 0));
        equipTableBR.setSelectionBackground(new java.awt.Color(0, 0, 0));
        equipTableBR.setSelectionForeground(new java.awt.Color(255, 255, 255));
        equipTableBR.setShowGrid(true);
        equipTableBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipTableBRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(equipTableBR);
        if (equipTableBR.getColumnModel().getColumnCount() > 0) {
            equipTableBR.getColumnModel().getColumn(0).setMinWidth(100);
            equipTableBR.getColumnModel().getColumn(0).setPreferredWidth(100);
            equipTableBR.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 96, 79));
        jLabel2.setText("Equipment ID ");

        jLabel3.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 96, 79));
        jLabel3.setText("Equipment Name ");

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 96, 79));
        jLabel4.setText("Status");

        equipIDBR.setBackground(new java.awt.Color(204, 204, 204));
        equipIDBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        equipIDBR.setForeground(new java.awt.Color(0, 0, 0));

        equipNameBR.setBackground(new java.awt.Color(204, 204, 204));
        equipNameBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        equipNameBR.setForeground(new java.awt.Color(0, 0, 0));

        equipStatusBR.setBackground(new java.awt.Color(204, 204, 204));
        equipStatusBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        equipStatusBR.setForeground(new java.awt.Color(0, 0, 0));
        equipStatusBR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Functional", "Under Maintainance", "Malfunctional" }));
        equipStatusBR.setBorder(null);
        equipStatusBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipStatusBRActionPerformed(evt);
            }
        });

        updateBR.setBackground(new java.awt.Color(115, 96, 79));
        updateBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        updateBR.setForeground(new java.awt.Color(255, 255, 255));
        updateBR.setText("UPDATE");
        updateBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBRMouseClicked(evt);
            }
        });
        updateBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBRActionPerformed(evt);
            }
        });

        deleteBR.setBackground(new java.awt.Color(115, 96, 79));
        deleteBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        deleteBR.setForeground(new java.awt.Color(255, 255, 255));
        deleteBR.setText("DELETE");
        deleteBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBRMouseClicked(evt);
            }
        });

        clearBR.setBackground(new java.awt.Color(115, 96, 79));
        clearBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearBR.setForeground(new java.awt.Color(255, 255, 255));
        clearBR.setText("CLEAR");
        clearBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBRMouseClicked(evt);
            }
        });

        addBR.setBackground(new java.awt.Color(115, 96, 79));
        addBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addBR.setForeground(new java.awt.Color(255, 255, 255));
        addBR.setText("ADD");
        addBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBRMouseClicked(evt);
            }
        });
        addBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBRActionPerformed(evt);
            }
        });

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("Go Back");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(addBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBR)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(equipStatusBR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(equipNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(equipIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(117, 117, 117))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(159, 159, 159))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addComponent(jSeparator1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equipStatusBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(clearBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 940, 570));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper (2).jpg"))); // NOI18N
        jPanel3.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipStatusBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipStatusBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipStatusBRActionPerformed

    private void updateBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBRActionPerformed

    private void addBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBRActionPerformed

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
      new BakerDashboard().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

    private void equipTableBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipTableBRMouseClicked
        DefaultTableModel model = (DefaultTableModel) equipTableBR.getModel();  // Assuming your table is named `equipmentTableBR`
        int MyIndex = equipTableBR.getSelectedRow();  // Get the selected row index

// Check if any row is selected
if (MyIndex != -1) {
    // Retrieve values from the selected row and set them to the input fields
    equipIDBR.setText(model.getValueAt(MyIndex, 0).toString()); // Set Equipment ID
    equipNameBR.setText(model.getValueAt(MyIndex, 1).toString()); // Set Equipment Name
    equipStatusBR.setSelectedItem(model.getValueAt(MyIndex, 2).toString()); // Set Equipment Status (ComboBox)
} else {
    JOptionPane.showMessageDialog(this, "Please select an equipment record to edit.");
}

    }//GEN-LAST:event_equipTableBRMouseClicked

    private void addBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBRMouseClicked
        // Check if any required fields are empty
if (equipNameBR.getText().isEmpty() || equipStatusBR.getSelectedIndex() == -1) {
    JOptionPane.showMessageDialog(this, "Missing Information");
} else {
    try {
        // Proceed with inserting into Equipment table (no need to provide equipment_id as it's auto-increment)
        String query = "INSERT INTO Equipment (equipment_name, equipment_status) VALUES (?, ?)";

        PreparedStatement addStmt = Con.prepareStatement(query);
        
        // Set values for the insert statement
        addStmt.setString(1, equipNameBR.getText());  // Equipment Name
        addStmt.setString(2, equipStatusBR.getSelectedItem().toString());  // Equipment Status (from JComboBox)

        // Execute the insert query
        int row = addStmt.executeUpdate();

        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Equipment Record Saved!");
            loadEquipIntoTable();  // Refresh the table
            Clear();  // Clear the input fields
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in fields.");
    }
}

    }//GEN-LAST:event_addBRMouseClicked

    private void clearBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBRMouseClicked
       Clear();
    }//GEN-LAST:event_clearBRMouseClicked

    private void updateBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBRMouseClicked
        if (equipIDBR.getText().isEmpty() || equipStatusBR.getSelectedIndex() == -1 || equipNameBR.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Equipment ID, Name, or Status is missing.");
} else {
    try {
        // Parse the values from the input fields
        int equipmentID = Integer.parseInt(equipIDBR.getText());  // Equipment ID
        String equipmentStatus = equipStatusBR.getSelectedItem().toString();  // Equipment Status (from JComboBox)
        String equipmentName = equipNameBR.getText();  // Equipment Name

        // Prepare the SQL query to update the equipment record
        String updateQuery = "UPDATE Equipment SET equipment_name = ?, equipment_status = ? WHERE equipment_id = ?";

        // Prepare the statement and set the parameters
        PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
        updateStmt.setString(1, equipmentName);  // Set new equipment name
        updateStmt.setString(2, equipmentStatus);  // Set new equipment status
        updateStmt.setInt(3, equipmentID);  // Set the equipment ID

        // Execute the update query
        int result = updateStmt.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Equipment details updated successfully!");
            loadEquipIntoTable();  // Refresh the table with the updated data
            Clear();  // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "Equipment not found or update failed.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input for equipment ID.");
    }
}

    }//GEN-LAST:event_updateBRMouseClicked

    private void deleteBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBRMouseClicked
        if (equipIDBR.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Information is Missing");
} else {
    String equipmentID = equipIDBR.getText().trim();  // Get the input from the user
    String query = "DELETE FROM Equipment WHERE equipment_id = ?";  // SQL query for deletion

    try (PreparedStatement stmt = Con.prepareStatement(query)) {
        // Convert the Equipment ID from String to Integer
        stmt.setInt(1, Integer.parseInt(equipmentID));

        // Execute the delete operation
        int result = stmt.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Equipment Record Deleted!");
            loadEquipIntoTable();  // Refresh the table after deletion
            Clear();  // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "No Equipment Record Found with ID: " + equipmentID);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
        Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid format for Equipment ID");
    }
}

    }//GEN-LAST:event_deleteBRMouseClicked

    
    
    private void loadEquipIntoTable() {
    try {
        // SQL query to retrieve all data from the Production table
        String query = "SELECT * FROM equipment"; 

        // Prepare the statement and execute the query
        St = Con.prepareStatement(query);
        rst = St.executeQuery();

        // Get the metadata of the result set
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();

        // Get the DefaultTableModel of the JTable
        DefaultTableModel d = (DefaultTableModel) equipTableBR.getModel();

        // Clear existing rows before adding new ones
        d.setRowCount(0);

        // Iterate through the result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();

            // Add each column value to the vector (match column order)
            vc.add(rst.getString("equipment_id"));  
            vc.add(rst.getString("equipment_name"));
            vc.add(rst.getString("equipment_status")); 
            
            // Add the vector as a row in the table
            d.addRow(vc);
        }

        // Repaint the table to make sure it's updated
        equipTableBR.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(EquipManageB.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    private void Clear() {
    equipIDBR.setText("");
    equipNameBR.setText("");
    equipStatusBR.setSelectedIndex(0);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipManageB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipManageB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipManageB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipManageB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipManageB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton addBR;
    private javax.swing.JButton backBR;
    private javax.swing.JButton clearBR;
    private javax.swing.JButton deleteBR;
    private javax.swing.JTextField equipIDBR;
    private javax.swing.JTextField equipNameBR;
    private javax.swing.JComboBox<String> equipStatusBR;
    private javax.swing.JTable equipTableBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton updateBR;
    // End of variables declaration//GEN-END:variables
}
