/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baker;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Nouf
 */
public class InvCheckB extends javax.swing.JFrame {

    /**
     * Creates new form InvCheckB
     */
    public InvCheckB() {
        initComponents();
        Sqlconnector();
        loadIngIntoTable();
    }
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingTableBR = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ingIDBR = new javax.swing.JTextField();
        ingNameBR = new javax.swing.JTextField();
        updateBR = new javax.swing.JButton();
        addBR = new javax.swing.JButton();
        deleteBR = new javax.swing.JButton();
        clearBR = new javax.swing.JButton();
        ingQBR = new javax.swing.JSpinner();
        backBR = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ingStatusB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 96, 79));
        jLabel1.setText("Ingredients Inventory");

        ingTableBR.setBackground(new java.awt.Color(115, 96, 79));
        ingTableBR.setForeground(new java.awt.Color(0, 0, 0));
        ingTableBR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredient ID", "Ingredient Name", "Quantity(kg)", "Stock Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ingTableBR.setAutoscrolls(false);
        ingTableBR.setGridColor(new java.awt.Color(0, 0, 0));
        ingTableBR.setSelectionBackground(new java.awt.Color(0, 0, 0));
        ingTableBR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ingTableBR.setShowGrid(true);
        ingTableBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingTableBRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingTableBR);
        ingTableBR.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 96, 79));
        jLabel2.setText("Ingredient ID :");

        jLabel3.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 96, 79));
        jLabel3.setText("Ingredient Name :");

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 96, 79));
        jLabel5.setText("Quantity :");

        ingIDBR.setBackground(new java.awt.Color(204, 204, 204));
        ingIDBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        ingIDBR.setForeground(new java.awt.Color(0, 0, 0));

        ingNameBR.setBackground(new java.awt.Color(204, 204, 204));
        ingNameBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        ingNameBR.setForeground(new java.awt.Color(0, 0, 0));

        updateBR.setBackground(new java.awt.Color(115, 96, 79));
        updateBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        updateBR.setForeground(new java.awt.Color(255, 255, 255));
        updateBR.setText("UPDATE");
        updateBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBRMouseClicked(evt);
            }
        });

        addBR.setBackground(new java.awt.Color(115, 96, 79));
        addBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addBR.setForeground(new java.awt.Color(255, 255, 255));
        addBR.setText("ADD");
        addBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBRMouseClicked(evt);
            }
        });
        addBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBRActionPerformed(evt);
            }
        });

        deleteBR.setBackground(new java.awt.Color(115, 96, 79));
        deleteBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        deleteBR.setForeground(new java.awt.Color(255, 255, 255));
        deleteBR.setText("DELETE");
        deleteBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBRMouseClicked(evt);
            }
        });

        clearBR.setBackground(new java.awt.Color(115, 96, 79));
        clearBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearBR.setForeground(new java.awt.Color(255, 255, 255));
        clearBR.setText("CLEAR");
        clearBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBRMouseClicked(evt);
            }
        });

        ingQBR.setBorder(null);

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("Go Back");
        backBR.setBorder(null);
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        ingStatusB.setBackground(new java.awt.Color(204, 204, 204));
        ingStatusB.setEditable(true);
        ingStatusB.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        ingStatusB.setForeground(new java.awt.Color(0, 0, 0));
        ingStatusB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low ", "Full" }));
        ingStatusB.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 96, 79));
        jLabel6.setText("Stock Status :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(addBR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updateBR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteBR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(74, 74, 74))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ingQBR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ingStatusB, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ingIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ingNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel3)))
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingQBR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingStatusB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 940, 570));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper (2).jpg"))); // NOI18N
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBRActionPerformed

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
      new BakerDashboard().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_backBRActionPerformed

    private void ingTableBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingTableBRMouseClicked
        DefaultTableModel model = (DefaultTableModel) ingTableBR.getModel();
        int MyIndex = ingTableBR.getSelectedRow();
        ingIDBR.setText(model.getValueAt(MyIndex, 0).toString());
        ingNameBR.setText(model.getValueAt(MyIndex, 1).toString());
        ingQBR.setValue(Integer.parseInt(model.getValueAt(MyIndex, 2).toString())); 
        ingStatusB.setSelectedItem(model.getValueAt(MyIndex, 3).toString());

    }//GEN-LAST:event_ingTableBRMouseClicked

    private void addBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBRMouseClicked
       // Check if any required fields are empty
       if (ingNameBR.getText().isEmpty() || 
    ingQBR.getValue() == null || 
    ingStatusB.getSelectedIndex() == -1) {
    JOptionPane.showMessageDialog(this, "Missing Information");
       } else {
    try {
        // Proceed with the insert (no need to check for ingredient_id)
        String query = "INSERT INTO Ingredients (ingredient_name, ingredient_quantity, stock_status) VALUES (?, ?, ?)";
        PreparedStatement addStmt = Con.prepareStatement(query);
        
        // Set values for the insert statement
        addStmt.setString(1, ingNameBR.getText());  // Ingredient Name
        addStmt.setInt(2, (Integer) ingQBR.getValue());  // JSpinner value for Ingredient Quantity
        addStmt.setString(3, ingStatusB.getSelectedItem().toString());  // Ingredient Status
        
        // Execute the insert query
        int row = addStmt.executeUpdate();
        
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient Saved!");
            loadIngIntoTable();  // Refresh the table
            Clear();  // Clear the input fields
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in Ingredient Quantity.");
    }
}

    }//GEN-LAST:event_addBRMouseClicked

    private void clearBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBRMouseClicked
        Clear();
    }//GEN-LAST:event_clearBRMouseClicked

    private void updateBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBRMouseClicked

        DefaultTableModel model = (DefaultTableModel) ingTableBR.getModel();
        int selectedRow = ingTableBR.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an Ingredient to edit.");
            return;
        }

        try {
    // Retrieve the Ingredient ID from the input field (which corresponds to the selected row)
    int ingredientID = Integer.parseInt(ingIDBR.getText().trim());
    String ingredientName = ingNameBR.getText().trim();  // Get text from JTextField
    int ingredientQuantity = (Integer) ingQBR.getValue();  // Get value from JSpinner
    String ingredientStatus = ingStatusB.getSelectedItem().toString();  // Get selected item from JComboBox
    
    // Validation: Check if the required fields are not empty
    if (ingredientName.isEmpty() || ingIDBR.getText().isEmpty() || ingredientStatus.isEmpty()) {  // Check if the text fields are empty
        JOptionPane.showMessageDialog(this, "Please ensure all fields are filled correctly.");
        return;
    }

    // Update query to modify the ingredient in the database
    String query = "UPDATE Ingredients SET ingredient_name=?, ingredient_quantity=?, Stock_status=? WHERE ingredient_id=?";
    
    try (PreparedStatement st = Con.prepareStatement(query)) {
        // Set the prepared statement parameters
        st.setString(1, ingredientName);
        st.setInt(2, ingredientQuantity);
        st.setString(3, ingredientStatus);
        st.setInt(4, ingredientID);

        // Execute the update
        int result = st.executeUpdate();
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient updated successfully.");
            loadIngIntoTable();  // Refresh the table after the update
            Clear();  // Clear the input fields after the update
        } else {
            JOptionPane.showMessageDialog(this, "No ingredient found with ID: " + ingredientID + ", update failed.");
        }
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Invalid number format in Ingredient ID or Quantity fields.");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database access error: " + ex.getMessage());
    Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_updateBRMouseClicked

    private void deleteBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBRMouseClicked
        if (ingIDBR.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Information is Missing");
        } else {
    String ingredientID = ingIDBR.getText().trim();
    String query = "DELETE FROM Ingredients WHERE ingredient_id = ?";  

    try (PreparedStatement stmt = Con.prepareStatement(query)) {
        // Convert the Ingredient ID from String to Integer
        stmt.setInt(1, Integer.parseInt(ingredientID));

        // Execute the delete operation
        int result = stmt.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Ingredient Deleted!");
            loadIngIntoTable();  // Refresh the table after deletion
            Clear();  // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "No Ingredient Found with ID: " + ingredientID);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
        Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid format for Ingredient ID");
    }
}

    }//GEN-LAST:event_deleteBRMouseClicked

    private void loadIngIntoTable() {
    try {
        // SQL query to join Products and Recipes tables using product_name
        String query = "SELECT * from ingredients";
        
        // Prepare the statement and execute the query
        St = Con.prepareStatement(query);
        rst = St.executeQuery();
        
        // Get the metadata of the result set
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();
        
        // Get the DefaultTableModel of the JTable
        DefaultTableModel d = (DefaultTableModel) ingTableBR.getModel();
        
        // Clear existing rows before adding new ones
        d.setRowCount(0);
        
        // Iterate through the result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();
            
            // Add each column value to the vector (match column order)
            vc.add(rst.getString("ingredient_id")); 
            vc.add(rst.getString("ingredient_name"));
            vc.add(rst.getInt("ingredient_quantity")); 
            vc.add(rst.getString("Stock_Status")); 
            
            // Add the vector as a row in the table
            d.addRow(vc);
        }

        // Repaint the table to make sure it's updated
        ingTableBR.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void Clear() {
    ingIDBR.setText("");
    ingNameBR.setText("");
    ingQBR.setValue(0);
    ingStatusB.setSelectedIndex(0);
    
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvCheckB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvCheckB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvCheckB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvCheckB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvCheckB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton addBR;
    private javax.swing.JButton backBR;
    private javax.swing.JButton clearBR;
    private javax.swing.JButton deleteBR;
    private javax.swing.JTextField ingIDBR;
    private javax.swing.JTextField ingNameBR;
    private javax.swing.JSpinner ingQBR;
    private javax.swing.JComboBox<String> ingStatusB;
    private javax.swing.JTable ingTableBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton updateBR;
    // End of variables declaration//GEN-END:variables
}
