/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baker;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nouf
 */
public class RecipeB extends javax.swing.JFrame {


    public RecipeB() {
        initComponents();
        Sqlconnector();
        loadRecipeIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recipeTableBR = new javax.swing.JTable();
        backBR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        recipeIDBR = new javax.swing.JTextField();
        prodPrepB = new javax.swing.JTextField();
        recipeBR = new javax.swing.JTextField();
        categoryBR = new javax.swing.JComboBox<>();
        updateBR = new javax.swing.JButton();
        addBR = new javax.swing.JButton();
        deleteBR = new javax.swing.JButton();
        clearBR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        prodNameBR = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 96, 79));
        jLabel1.setText("Recipe Management");
        backBut.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 6, -1, -1));

        recipeTableBR.setBackground(new java.awt.Color(115, 96, 79));
        recipeTableBR.setForeground(new java.awt.Color(0, 0, 0));
        recipeTableBR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recipe ID", "Product Name", "Category", "Preperation Time", "Recipe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recipeTableBR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recipeTableBR.setGridColor(new java.awt.Color(0, 0, 0));
        recipeTableBR.setRequestFocusEnabled(false);
        recipeTableBR.setSelectionBackground(new java.awt.Color(0, 0, 0));
        recipeTableBR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        recipeTableBR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        recipeTableBR.setShowGrid(true);
        recipeTableBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recipeTableBRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recipeTableBR);
        recipeTableBR.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        backBut.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 69, 563, 468));

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("Go Back");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });
        backBut.add(backBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 94, 35));

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 96, 79));
        jLabel2.setText("Recipe ID :");
        backBut.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 96, 79));
        jLabel3.setText("Product Name :");
        backBut.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 161, -1, -1));

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 96, 79));
        jLabel4.setText("Category :");
        backBut.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 208, -1, -1));

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 96, 79));
        jLabel6.setText("Recipe ");
        backBut.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 302, -1, -1));

        recipeIDBR.setBackground(new java.awt.Color(204, 204, 204));
        recipeIDBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        recipeIDBR.setForeground(new java.awt.Color(0, 0, 0));
        backBut.add(recipeIDBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 106, 212, -1));

        prodPrepB.setBackground(new java.awt.Color(204, 204, 204));
        prodPrepB.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodPrepB.setForeground(new java.awt.Color(0, 0, 0));
        backBut.add(prodPrepB, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 250, 211, -1));

        recipeBR.setBackground(new java.awt.Color(204, 204, 204));
        recipeBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        recipeBR.setForeground(new java.awt.Color(0, 0, 0));
        recipeBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeBRActionPerformed(evt);
            }
        });
        backBut.add(recipeBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 330, 336, 165));

        categoryBR.setBackground(new java.awt.Color(204, 204, 204));
        categoryBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        categoryBR.setForeground(new java.awt.Color(0, 0, 0));
        categoryBR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bread", "Pastery", "Cakes", "Cookies", "Pies" }));
        categoryBR.setBorder(null);
        categoryBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBRActionPerformed(evt);
            }
        });
        backBut.add(categoryBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 206, 211, -1));

        updateBR.setBackground(new java.awt.Color(115, 96, 79));
        updateBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        updateBR.setForeground(new java.awt.Color(255, 255, 255));
        updateBR.setText("UPDATE");
        updateBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBRMouseClicked(evt);
            }
        });
        backBut.add(updateBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 507, -1, 30));

        addBR.setBackground(new java.awt.Color(115, 96, 79));
        addBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addBR.setForeground(new java.awt.Color(255, 255, 255));
        addBR.setText("ADD");
        addBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBRMouseClicked(evt);
            }
        });
        addBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBRActionPerformed(evt);
            }
        });
        backBut.add(addBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 507, -1, 30));

        deleteBR.setBackground(new java.awt.Color(115, 96, 79));
        deleteBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        deleteBR.setForeground(new java.awt.Color(255, 255, 255));
        deleteBR.setText("DELETE");
        deleteBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBRMouseClicked(evt);
            }
        });
        backBut.add(deleteBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 507, -1, 30));

        clearBR.setBackground(new java.awt.Color(115, 96, 79));
        clearBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearBR.setForeground(new java.awt.Color(255, 255, 255));
        clearBR.setText("CLEAR");
        clearBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBRMouseClicked(evt);
            }
        });
        backBut.add(clearBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 507, -1, 30));

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 96, 79));
        jLabel5.setText("Prep Time :");
        backBut.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 255, -1, -1));

        prodNameBR.setBackground(new java.awt.Color(204, 204, 204));
        prodNameBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodNameBR.setForeground(new java.awt.Color(0, 0, 0));
        backBut.add(prodNameBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 156, 212, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        backBut.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 294, 336, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        backBut.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 1000, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBRMouseClicked
        Clear();
    }//GEN-LAST:event_clearBRMouseClicked

    private void deleteBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBRMouseClicked

        if (recipeIDBR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information is Missing");
        } else {
            String BID = recipeIDBR.getText().trim();
            String query = "DELETE FROM recipes WHERE recipe_id = ?";  // Use correct column name for recipe ID

            try (PreparedStatement stmt = Con.prepareStatement(query)) {
                // Convert the Recipe ID from String to Integer
                stmt.setInt(1, Integer.parseInt(BID));

                // Execute the delete operation
                int result = stmt.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Recipe Deleted!");
                    loadRecipeIntoTable();  // Refresh the table after deletion
                    Clear();  // Clear the input fields
                } else {
                    JOptionPane.showMessageDialog(this, "No Recipe Found with ID: " + BID);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
                Logger.getLogger(RecipeB.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid format for Recipe ID");
            }
        }

    }//GEN-LAST:event_deleteBRMouseClicked

    private void addBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBRActionPerformed

    private void addBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBRMouseClicked

        if (recipeIDBR.getText().isEmpty() || prodNameBR.getText().isEmpty() ||
            categoryBR.getSelectedIndex() == -1 || prodPrepB.getText().isEmpty() || recipeBR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                // Step 1: Validate if the Recipe ID already exists
                String checkQuery = "SELECT COUNT(*) FROM recipes WHERE recipe_id = ?";
                PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
                checkStmt.setInt(1, Integer.parseInt(recipeIDBR.getText().trim()));  // Check for duplicate recipeID
                ResultSet rs = checkStmt.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    // Step 2: If the recipeID already exists, display a message and return
                    JOptionPane.showMessageDialog(this, "Recipe ID already exists. Please use a unique Recipe ID.");
                } else {
                    // Step 3: If no duplicate, proceed with the insert
                    PreparedStatement add = Con.prepareStatement("INSERT INTO recipes (recipe_id, product_name, category, preparation_time, recipe_instructions) VALUES (?, ?, ?, ?, ?)");
                    add.setInt(1, Integer.parseInt(recipeIDBR.getText()));  // Set Recipe ID
                    add.setString(2, prodNameBR.getText());  // Set Product Name
                    add.setString(3, categoryBR.getSelectedItem().toString());  // Set Category
                    add.setInt(4, Integer.parseInt(prodPrepB.getText()));  // Set Preparation Time
                    add.setString(5, recipeBR.getText());  // Set Recipe Instructions

                    // Step 4: Execute the insert query
                    int row = add.executeUpdate();
                    if (row > 0) {
                        JOptionPane.showMessageDialog(this, "Recipe Saved!");
                        loadRecipeIntoTable();  // Refresh the table after insertion
                        Clear();  // Clear the input fields
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error while saving the recipe.");
            }
        }
    }//GEN-LAST:event_addBRMouseClicked

    private void updateBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBRMouseClicked

        DefaultTableModel model = (DefaultTableModel) recipeTableBR.getModel();
        int selectedRow = recipeTableBR.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a Recipe to edit.");
            return;
        }

        try {
            // Retrieve the Recipe ID from the input field (which corresponds to the selected row)
            int recipeID = Integer.parseInt(recipeIDBR.getText().trim());
            String productName = prodNameBR.getText().trim();
            String category = categoryBR.getSelectedItem().toString();
            int preparationTime = Integer.parseInt(prodPrepB.getText().trim());
            String recipeInstructions = recipeBR.getText().trim();

            // Validation: Check if the required fields are not empty
            if (productName.isEmpty() || recipeIDBR.getText().isEmpty() || category.isEmpty() || recipeInstructions.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please ensure all fields are filled correctly.");
                return;
            }

            // Update query to modify the recipe in the database
            String query = "UPDATE recipes SET product_name=?, category=?, preparation_time=?, recipe_instructions=? WHERE recipe_id=?";

            try (PreparedStatement st = Con.prepareStatement(query)) {
                // Set the prepared statement parameters
                st.setString(1, productName);
                st.setString(2, category);
                st.setInt(3, preparationTime);
                st.setString(4, recipeInstructions);
                st.setInt(5, recipeID);

                // Execute the update
                int result = st.executeUpdate();
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Recipe updated successfully.");
                    loadRecipeIntoTable();  // Refresh the table after the update
                    Clear();  // Clear the input fields after the update
                } else {
                    JOptionPane.showMessageDialog(this, "No recipe found with ID: " + recipeID + ", update failed.");
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format in Recipe ID or Preparation Time fields.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database access error: " + ex.getMessage());
            Logger.getLogger(RecipeB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateBRMouseClicked

    private void categoryBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBRActionPerformed

    private void recipeBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeBRActionPerformed

    private void recipeTableBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recipeTableBRMouseClicked
        DefaultTableModel model = (DefaultTableModel)recipeTableBR.getModel();
        int MyIndex = recipeTableBR.getSelectedRow();
        recipeIDBR.setText(model.getValueAt(MyIndex, 0).toString());
        prodNameBR.setText(model.getValueAt(MyIndex, 1).toString());
        categoryBR.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        prodPrepB.setText(model.getValueAt(MyIndex, 3).toString());
        recipeBR.setText(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_recipeTableBRMouseClicked

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
        new BakerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;
    
    void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(RecipeB.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(RecipeB.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
 
private void loadRecipeIntoTable() {
    try {
        // SQL query to join Products and Recipes tables using product_name
        String query = "SELECT * from recipes";
        
        // Prepare the statement and execute the query
        St = Con.prepareStatement(query);
        rst = St.executeQuery();
        
        // Get the metadata of the result set
        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();
        
        // Get the DefaultTableModel of the JTable
        DefaultTableModel d = (DefaultTableModel) recipeTableBR.getModel();
        
        // Clear existing rows before adding new ones
        d.setRowCount(0);
        
        // Iterate through the result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();
            
            // Add each column value to the vector (match column order)
            vc.add(rst.getString("recipe_id")); // Recipe ID
            vc.add(rst.getString("product_name")); // Product Name
            vc.add(rst.getString("category")); // Category
            vc.add(rst.getInt("preparation_time")); // Preparation Time
            vc.add(rst.getString("recipe_instructions")); // Recipe Instructions
            
            // Add the vector as a row in the table
            d.addRow(vc);
        }

        // Repaint the table to make sure it's updated
        recipeTableBR.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(RecipeB.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void Clear() {
    recipeIDBR.setText("");
    prodNameBR.setText("");
    categoryBR.setSelectedIndex(0);
    prodPrepB.setText("");
    recipeBR.setText("");
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         RecipeB RB = new RecipeB();
         RB.Sqlconnector();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeB().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBR;
    private javax.swing.JButton backBR;
    private javax.swing.JPanel backBut;
    private javax.swing.JComboBox<String> categoryBR;
    private javax.swing.JButton clearBR;
    private javax.swing.JButton deleteBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField prodNameBR;
    private javax.swing.JTextField prodPrepB;
    private javax.swing.JTextField recipeBR;
    private javax.swing.JTextField recipeIDBR;
    private javax.swing.JTable recipeTableBR;
    private javax.swing.JButton updateBR;
    // End of variables declaration//GEN-END:variables
}
