/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baker;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author Nouf
 */
public class RecordKeepB extends javax.swing.JFrame {

    /**
     * Creates new form RecordKeepB
     */
    public RecordKeepB() {
        initComponents();
        Sqlconnector();
        loadProdIntoTable();
    }
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(RecordKeepB.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(RecordKeepB.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodTableBR = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PIDB = new javax.swing.JTextField();
        prodNameBR = new javax.swing.JTextField();
        prodBatchBR = new javax.swing.JTextField();
        pDateBR = new javax.swing.JTextField();
        prodCatBR = new javax.swing.JComboBox<>();
        updateBR = new javax.swing.JButton();
        addBR = new javax.swing.JButton();
        deleteBR = new javax.swing.JButton();
        clearBR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        backBR = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        prodIDBR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        prodExpiryBR = new javax.swing.JTextField();
        prodQBR = new javax.swing.JSpinner();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 96, 79));
        jLabel1.setText("Production Records");

        prodTableBR.setBackground(new java.awt.Color(115, 96, 79));
        prodTableBR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Production ID", "Prod ID", "Name", "Category", "Batch ", "Quantity", "Expiry ", "Production Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodTableBR.setGridColor(new java.awt.Color(0, 0, 0));
        prodTableBR.setSelectionBackground(new java.awt.Color(0, 0, 0));
        prodTableBR.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prodTableBR.setShowGrid(true);
        prodTableBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodTableBRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodTableBR);
        prodTableBR.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (prodTableBR.getColumnModel().getColumnCount() > 0) {
            prodTableBR.getColumnModel().getColumn(0).setMinWidth(80);
            prodTableBR.getColumnModel().getColumn(0).setPreferredWidth(80);
            prodTableBR.getColumnModel().getColumn(0).setMaxWidth(80);
            prodTableBR.getColumnModel().getColumn(1).setMinWidth(40);
            prodTableBR.getColumnModel().getColumn(1).setPreferredWidth(40);
            prodTableBR.getColumnModel().getColumn(1).setMaxWidth(40);
            prodTableBR.getColumnModel().getColumn(3).setMinWidth(70);
            prodTableBR.getColumnModel().getColumn(3).setPreferredWidth(70);
            prodTableBR.getColumnModel().getColumn(3).setMaxWidth(70);
            prodTableBR.getColumnModel().getColumn(5).setMinWidth(50);
            prodTableBR.getColumnModel().getColumn(5).setPreferredWidth(50);
            prodTableBR.getColumnModel().getColumn(5).setMaxWidth(50);
            prodTableBR.getColumnModel().getColumn(6).setMinWidth(90);
            prodTableBR.getColumnModel().getColumn(6).setPreferredWidth(90);
            prodTableBR.getColumnModel().getColumn(6).setMaxWidth(90);
            prodTableBR.getColumnModel().getColumn(7).setMinWidth(90);
            prodTableBR.getColumnModel().getColumn(7).setPreferredWidth(100);
            prodTableBR.getColumnModel().getColumn(7).setMaxWidth(90);
        }

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 96, 79));
        jLabel2.setText("Production ID");

        jLabel3.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 96, 79));
        jLabel3.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 96, 79));
        jLabel4.setText("Category ");

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 96, 79));
        jLabel5.setText("Batch Number");

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(115, 96, 79));
        jLabel6.setText("Expiry Date ");

        PIDB.setBackground(new java.awt.Color(204, 204, 204));
        PIDB.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        PIDB.setForeground(new java.awt.Color(0, 0, 0));

        prodNameBR.setBackground(new java.awt.Color(204, 204, 204));
        prodNameBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodNameBR.setForeground(new java.awt.Color(0, 0, 0));

        prodBatchBR.setBackground(new java.awt.Color(204, 204, 204));
        prodBatchBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodBatchBR.setForeground(new java.awt.Color(0, 0, 0));

        pDateBR.setBackground(new java.awt.Color(204, 204, 204));
        pDateBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        pDateBR.setForeground(new java.awt.Color(0, 0, 0));
        pDateBR.setText("Current Date");
        pDateBR.setEnabled(false);
        pDateBR.setSelectionColor(new java.awt.Color(51, 153, 255));
        pDateBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDateBRActionPerformed(evt);
            }
        });

        prodCatBR.setBackground(new java.awt.Color(204, 204, 204));
        prodCatBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodCatBR.setForeground(new java.awt.Color(0, 0, 0));
        prodCatBR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bread", "Pastery", "Cakes", "Cookies", "Pies" }));
        prodCatBR.setBorder(null);
        prodCatBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCatBRActionPerformed(evt);
            }
        });

        updateBR.setBackground(new java.awt.Color(115, 96, 79));
        updateBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        updateBR.setForeground(new java.awt.Color(255, 255, 255));
        updateBR.setText("UPDATE");
        updateBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBRMouseClicked(evt);
            }
        });

        addBR.setBackground(new java.awt.Color(115, 96, 79));
        addBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        addBR.setForeground(new java.awt.Color(255, 255, 255));
        addBR.setText("ADD");
        addBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBRMouseClicked(evt);
            }
        });
        addBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBRActionPerformed(evt);
            }
        });

        deleteBR.setBackground(new java.awt.Color(115, 96, 79));
        deleteBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        deleteBR.setForeground(new java.awt.Color(255, 255, 255));
        deleteBR.setText("DELETE");
        deleteBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBRMouseClicked(evt);
            }
        });

        clearBR.setBackground(new java.awt.Color(115, 96, 79));
        clearBR.setFont(new java.awt.Font("Footlight MT Light", 1, 12)); // NOI18N
        clearBR.setForeground(new java.awt.Color(255, 255, 255));
        clearBR.setText("CLEAR");
        clearBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBRMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(115, 96, 79));
        jLabel7.setText("Product Quantity ");

        backBR.setBackground(new java.awt.Color(255, 255, 255));
        backBR.setFont(new java.awt.Font("Aparajita", 1, 14)); // NOI18N
        backBR.setForeground(new java.awt.Color(0, 0, 0));
        backBR.setText("Go Back");
        backBR.setBorder(null);
        backBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBRMouseClicked(evt);
            }
        });
        backBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBRActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(115, 96, 79));
        jLabel8.setText("Product ID");

        prodIDBR.setBackground(new java.awt.Color(204, 204, 204));
        prodIDBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodIDBR.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(115, 96, 79));
        jLabel9.setText("Production Date ");

        prodExpiryBR.setBackground(new java.awt.Color(204, 204, 204));
        prodExpiryBR.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        prodExpiryBR.setForeground(new java.awt.Color(0, 0, 0));
        prodExpiryBR.setSelectionColor(new java.awt.Color(51, 153, 255));
        prodExpiryBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodExpiryBRActionPerformed(evt);
            }
        });

        prodQBR.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(addBR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(updateBR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(prodExpiryBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(deleteBR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clearBR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(pDateBR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(PIDB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addComponent(prodIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel3)
                                                .addGap(118, 118, 118)
                                                .addComponent(jLabel4))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel6)
                                                .addGap(105, 105, 105)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                    .addComponent(prodBatchBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(prodQBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(99, 99, 99)
                                                        .addComponent(jLabel7))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(prodNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(63, 63, 63)
                                                        .addComponent(prodCatBR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(136, 136, 136))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addComponent(jSeparator1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(backBR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PIDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodIDBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodNameBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodCatBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prodBatchBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodQBR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pDateBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodExpiryBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 940, 570));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper (2).jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodExpiryBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodExpiryBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodExpiryBRActionPerformed

    private void backBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBRActionPerformed

    private void backBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBRMouseClicked
        new BakerDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBRMouseClicked

    private void clearBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBRMouseClicked
        Clear();
    }//GEN-LAST:event_clearBRMouseClicked

    private void deleteBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBRMouseClicked
        if (PIDB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information is Missing");
        } else {
            String productionID = PIDB.getText().trim();  // Get the input from the user
            String selectQuery = "SELECT product_id, quantity FROM Production WHERE production_id = ?";
            String deleteQuery = "DELETE FROM Production WHERE production_id = ?";
            String updateQuery = "UPDATE Products SET quantity = quantity - ? WHERE product_id = ?";  // Deduct quantity in Products table

            try (PreparedStatement selectStmt = Con.prepareStatement(selectQuery)) {
                // Step 1: Retrieve the quantity and product_id from the Production table before deleting
                selectStmt.setInt(1, Integer.parseInt(productionID));  // Set the production_id
                ResultSet rs = selectStmt.executeQuery();

                if (rs.next()) {
                    int productID = rs.getInt("product_id");  // Get the product_id from the Production table
                    int productionQuantity = rs.getInt("quantity");  // Get the quantity from the Production table

                    // Step 2: Proceed with deleting the record from the Production table
                    try (PreparedStatement deleteStmt = Con.prepareStatement(deleteQuery)) {
                        deleteStmt.setInt(1, Integer.parseInt(productionID));  // Set the production_id for deletion

                        int deleteResult = deleteStmt.executeUpdate();

                        if (deleteResult > 0) {
                            // Step 3: Update the Products table to deduct the quantity
                            try (PreparedStatement updateStmt = Con.prepareStatement(updateQuery)) {
                                updateStmt.setInt(1, productionQuantity);  // Set the quantity to be deducted
                                updateStmt.setInt(2, productID);  // Set the product_id for the update

                                int updateResult = updateStmt.executeUpdate();

                                if (updateResult > 0) {
                                    JOptionPane.showMessageDialog(this, "Production Record Deleted and Quantity Updated in Products!");
                                    loadProdIntoTable();  // Refresh the table with updated data
                                    Clear();  // Clear the input fields
                                }
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Production Record Found with ID: " + productionID);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error in database operation: " + ex.getMessage());
                Logger.getLogger(InvCheckB.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid format for Production ID");
            }
        }
    }//GEN-LAST:event_deleteBRMouseClicked

    private void addBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBRActionPerformed

    private void addBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBRMouseClicked

        if (prodIDBR.getText().isEmpty() || prodNameBR.getText().isEmpty() ||
            prodCatBR.getSelectedIndex() == -1 || prodBatchBR.getText().isEmpty() ||
            prodQBR.getValue() == null || prodExpiryBR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                // Check if the product_id exists in the Products table
                String checkProductQuery = "SELECT COUNT(*) FROM Products WHERE product_id = ?";
                PreparedStatement checkProductStmt = Con.prepareStatement(checkProductQuery);
                checkProductStmt.setInt(1, Integer.parseInt(prodIDBR.getText()));  // Check for existing product_id
                ResultSet rs = checkProductStmt.executeQuery();

                if (rs.next() && rs.getInt(1) == 0) {
                    // If the product_id does not exist in the Products table
                    JOptionPane.showMessageDialog(this, "Product ID does not exist in the Products table.");
                } else {
                    // Proceed with inserting into Production table (no need to check production_id)
                    String query = "INSERT INTO Production (product_id, product_name, category, batch_number, quantity, expiry_date, production_date) VALUES (?, ?, ?, ?, ?, ?, ?)";

                    PreparedStatement addStmt = Con.prepareStatement(query);

                    // Set values for the insert statement
                    addStmt.setInt(1, Integer.parseInt(prodIDBR.getText())); // Product ID
                    addStmt.setString(2, prodNameBR.getText());  // Product Name
                    addStmt.setString(3, prodCatBR.getSelectedItem().toString());  // Category (from JComboBox)
                    addStmt.setString(4, prodBatchBR.getText());  // Batch Number
                    addStmt.setInt(5, (Integer) prodQBR.getValue());  // Product Quantity
                    addStmt.setDate(6, Date.valueOf(prodExpiryBR.getText()));  // Expiry Date
                    addStmt.setDate(7, new java.sql.Date(System.currentTimeMillis()));  // Production Date (current date)

                    // Execute the insert query
                    int row = addStmt.executeUpdate();

                    if (row > 0) {
                        JOptionPane.showMessageDialog(this, "Production Record Saved!");
                        loadProdIntoTable();  // Refresh the table
                        Clear();  // Clear the input fields
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid number format in Product ID or Quantity.");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(this, "Invalid date format for Expiry Date.");
            }
        }
    }//GEN-LAST:event_addBRMouseClicked

    private void updateBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBRMouseClicked
        if (PIDB.getText().isEmpty() || prodQBR.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Production ID or Quantity is missing.");
        } else {

            try {

                int productionID = Integer.parseInt(PIDB.getText());
                int quantity = (Integer) prodQBR.getValue();

                String updateQuery = "UPDATE Production SET quantity = ? WHERE production_id = ?";

                PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
                updateStmt.setInt(1, quantity);
                updateStmt.setInt(2, productionID);

                int result = updateStmt.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Product quantity updated successfully!");
                    loadProdIntoTable();
                    Clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Product not found or quantity update failed.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid input for product ID or quantity.");
            }
        }
    }//GEN-LAST:event_updateBRMouseClicked

    private void prodCatBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCatBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodCatBRActionPerformed

    private void pDateBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDateBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDateBRActionPerformed

    private void prodTableBRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodTableBRMouseClicked

        DefaultTableModel model = (DefaultTableModel) prodTableBR.getModel();
        int MyIndex = prodTableBR.getSelectedRow();

        if (MyIndex != -1) {
            prodIDBR.setText(model.getValueAt(MyIndex, 0).toString());
            prodIDBR.setText(model.getValueAt(MyIndex, 1).toString());
            prodNameBR.setText(model.getValueAt(MyIndex, 2).toString());
            prodCatBR.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
            prodBatchBR.setText(model.getValueAt(MyIndex, 4).toString());
            prodQBR.setValue(Integer.parseInt(model.getValueAt(MyIndex, 5).toString()));
            prodExpiryBR.setText(model.getValueAt(MyIndex, 6).toString());
            pDateBR.setText(model.getValueAt(MyIndex, 7).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Please select a production record to edit.");
        }
    }//GEN-LAST:event_prodTableBRMouseClicked

    
    private void loadProdIntoTable() {
    try {
        
        String query = "SELECT * FROM production";  

        St = Con.prepareStatement(query);
        rst = St.executeQuery();

        java.sql.ResultSetMetaData Rsd = rst.getMetaData();
        int c = Rsd.getColumnCount();

        DefaultTableModel d = (DefaultTableModel) prodTableBR.getModel();

        d.setRowCount(0);

        while (rst.next()) {
            Vector vc = new Vector();

            // Add each column value to the vector (match column order)
            vc.add(rst.getString("production_id"));  
            vc.add(rst.getString("product_id"));
            vc.add(rst.getString("product_name")); 
            vc.add(rst.getString("category"));  
            vc.add(rst.getString("batch_number"));  
            vc.add(rst.getInt("quantity"));  
            vc.add(rst.getDate("expiry_date")); 
            vc.add(rst.getDate("production_date"));

            d.addRow(vc);
        }
        
        prodTableBR.repaint();

    } catch (SQLException ex) {
        Logger.getLogger(RecordKeepB.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void Clear() {
    PIDB.setText("");
    prodIDBR.setText("");
    prodNameBR.setText("");
    prodCatBR.setSelectedIndex(0);
    prodBatchBR.setText("");
    prodQBR.setValue(0);
    prodExpiryBR.setText("");
    pDateBR.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordKeepB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordKeepB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordKeepB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordKeepB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordKeepB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField PIDB;
    private javax.swing.JButton addBR;
    private javax.swing.JButton backBR;
    private javax.swing.JButton clearBR;
    private javax.swing.JButton deleteBR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pDateBR;
    private javax.swing.JTextField prodBatchBR;
    private javax.swing.JComboBox<String> prodCatBR;
    private javax.swing.JTextField prodExpiryBR;
    private javax.swing.JTextField prodIDBR;
    private javax.swing.JTextField prodNameBR;
    private javax.swing.JSpinner prodQBR;
    private javax.swing.JTable prodTableBR;
    private javax.swing.JButton updateBR;
    // End of variables declaration//GEN-END:variables
}
