/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bakerymanagementsystem;
import Customer.CustDashboard;
import Manager.ManagerDashboard;
import Baker.BakerDashboard;
import Cashier.Mainpage;
import java.awt.Window;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nouf
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Sqlconnector();
    }
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginBut = new javax.swing.JButton();
        SignUpBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClearBut = new javax.swing.JButton();
        userIDL = new javax.swing.JTextField();
        passL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Role = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        LoginBut.setBackground(new java.awt.Color(102, 0, 0));
        LoginBut.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        LoginBut.setText("Login");
        LoginBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButMouseClicked(evt);
            }
        });
        LoginBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        SignUpBut.setBackground(new java.awt.Color(102, 0, 0));
        SignUpBut.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        SignUpBut.setText("SignUp");
        SignUpBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButMouseClicked(evt);
            }
        });
        SignUpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("User ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, 30));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        ClearBut.setBackground(new java.awt.Color(102, 0, 0));
        ClearBut.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        ClearBut.setText("Clear");
        ClearBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButMouseClicked(evt);
            }
        });
        jPanel1.add(ClearBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        userIDL.setBackground(new java.awt.Color(204, 204, 204));
        userIDL.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        userIDL.setForeground(new java.awt.Color(0, 0, 0));
        userIDL.setText(" ");
        jPanel1.add(userIDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 170, 30));

        passL.setBackground(new java.awt.Color(204, 204, 204));
        passL.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        passL.setForeground(new java.awt.Color(0, 0, 0));
        passL.setText(" ");
        passL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(passL, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 267, 170, 30));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Role");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        Role.setBackground(new java.awt.Color(204, 204, 204));
        Role.setFont(new java.awt.Font("Aparajita", 0, 14)); // NOI18N
        Role.setForeground(new java.awt.Color(0, 0, 0));
        Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Manager", "Cashier", "Baker" }));
        Role.setBorder(null);
        jPanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/11200577 (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButActionPerformed

    private void SignUpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButActionPerformed

    private void SignUpButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButMouseClicked
        Login L = new Login();
        SignUp SU = new SignUp();
        L.setVisible(false);
        SU.setVisible(true);
         
        L.dispose();
    }//GEN-LAST:event_SignUpButMouseClicked

    private void ClearButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButMouseClicked
      Clear();
    }//GEN-LAST:event_ClearButMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void LoginButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButMouseClicked
        String userName = userIDL.getText().trim();
String password = passL.getText().trim();

// Check if Username or Password is empty
if (userName.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Enter the Username and Password");
} else {
    // Get the selected role from JComboBox
    String selectedRole = Role.getSelectedItem().toString();

    try {
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        // Different queries for different user roles
        if (selectedRole.equals("Customer")) {
            // Customer: Search in Customer table
            String query = "SELECT * FROM Customer WHERE Customer_userID = ? AND Customerpassword = ?";
            ps = Con.prepareStatement(query);
            ps.setString(1, userName);
            ps.setString(2, password);
        } else {
            // Manager, Cashier, Baker: Search in users table
            String query = "SELECT * FROM users WHERE user_name = ? AND user_password = ?";
            ps = Con.prepareStatement(query);
            ps.setString(1, userName);
            ps.setString(2, password);
        }
        
        // Execute the query
        rs = ps.executeQuery();
        
        // Check if the user is found
        if (rs.next()) {
            // For Customer, open Customer Dashboard
            if (selectedRole.equals("Customer")) {
                new CustDashboard().setVisible(true);
                this.dispose();
            }
            // For Manager, open Manager Dashboard
            else if (selectedRole.equals("Manager")) {
                new ManagerDashboard().setVisible(true);
                this.dispose();
            }
            // For Cashier, open Cashier Dashboard
            else if (selectedRole.equals("Cashier")) {
                new Mainpage().setVisible(true);
                this.dispose();
            }
            // For Baker, open Baker Dashboard
            else if (selectedRole.equals("Baker")) {
                new BakerDashboard().setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Wrong Username or Password!");
            userIDL.setText("");
            passL.setText("");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Database error during login!");
    }
}

    }//GEN-LAST:event_LoginButMouseClicked

    private void Clear() {
    userIDL.setText("");
    passL.setText("");
    Role.setSelectedIndex(0);  
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBut;
    private javax.swing.JButton LoginBut;
    private javax.swing.JComboBox<String> Role;
    private javax.swing.JButton SignUpBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passL;
    private javax.swing.JTextField userIDL;
    // End of variables declaration//GEN-END:variables
}
