/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanisha
 */
public class CustPersonalInfo extends javax.swing.JFrame {

    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

    /**
     * Creates new form CustPersonalInfo
     */
    public CustPersonalInfo() {
        initComponents();
        Sqlconnector();
        setImage();
    }
    
    public void setImage(){
        
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/Images/20945443.jpg"));
        
        Image img1 = icon1.getImage().getScaledInstance(jLabelimage1.getWidth(),jLabelimage1.getHeight(),Image.SCALE_SMOOTH);
        
        jLabelimage1.setIcon(new ImageIcon(img1));
    }

   void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(CustPersonalInfo.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(CustPersonalInfo.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelid = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldpass = new javax.swing.JTextField();
        jLabelemail = new javax.swing.JLabel();
        jLabelname = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldaddress = new javax.swing.JTextField();
        jButtondel = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jLabelimage1 = new javax.swing.JLabel();
        jButtonclear1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Personal Information ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 490, 40));

        jPanelid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        jPanelid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("User ID: ");
        jPanelid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));
        jPanelid.add(jTextFieldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));

        jLabelemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelemail.setText("Password:");
        jPanelid.add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        jLabelname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelname.setText("Name: ");
        jPanelid.add(jLabelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        jLabeladdress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabeladdress.setText("Address: ");
        jPanelid.add(jLabeladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));
        jPanelid.add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, 30));
        jPanelid.add(jTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, 30));
        jPanelid.add(jTextFieldaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 220, 30));

        jButtondel.setBackground(new java.awt.Color(0, 102, 255));
        jButtondel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtondel.setForeground(new java.awt.Color(255, 255, 255));
        jButtondel.setText("Delete ");
        jButtondel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtondelMouseClicked(evt);
            }
        });
        jPanelid.add(jButtondel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 90, 30));

        jButtonupdate.setBackground(new java.awt.Color(0, 102, 255));
        jButtonupdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonupdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonupdate.setText("Update");
        jButtonupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonupdateMouseClicked(evt);
            }
        });
        jPanelid.add(jButtonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 30));
        jPanelid.add(jLabelimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 340, 340));

        jButtonclear1.setBackground(new java.awt.Color(0, 102, 255));
        jButtonclear1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonclear1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonclear1.setText("Clear");
        jButtonclear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonclear1MouseClicked(evt);
            }
        });
        jPanelid.add(jButtonclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 30));

        jPanel1.add(jPanelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 750, 420));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      new CustDashboard().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtondelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtondelMouseClicked

    if (jTextFieldid.getText().isEmpty() || jTextFieldname.getText().isEmpty()  || jTextFieldpass.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "ID, Name, Address, or Email is missing.");
} else {
    // Ask for confirmation before deletion
    int confirmation = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete this customer record?", 
        "Confirm Deletion", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirmation == JOptionPane.YES_OPTION) {
        try {
            // Parse the values from the input fields
            String id = jTextFieldid.getText();

            // Check if the user ID exists in the database
            String checkQuery = "SELECT COUNT(*) FROM customer WHERE Customer_userID = ?";
            PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
            checkStmt.setString(1, id);
            ResultSet rs = checkStmt.executeQuery();

            // If the user ID exists, proceed with the delete
            if (rs.next() && rs.getInt(1) > 0) {
                // Prepare the SQL query to delete the customer record
                String deleteQuery = "DELETE FROM customer WHERE Customer_userID = ?";

                // Prepare the statement and set the parameters
                PreparedStatement deleteStmt = Con.prepareStatement(deleteQuery);
                deleteStmt.setString(1, id);

                // Execute the delete query
                int result = deleteStmt.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Customer record deleted successfully.");
                    Clear(); // Clear input fields after successful deletion
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete customer record.");
                }
            } else {
                // If the user ID doesn't exist, show an error message
                JOptionPane.showMessageDialog(this, "User ID not found in the database.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input.");
        }
    } else {
        // If user clicks "No", clear all the input fields
        Clear();
    }
        }
     
    }//GEN-LAST:event_jButtondelMouseClicked

    private void jButtonupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonupdateMouseClicked
       if (jTextFieldid.getText().isEmpty() || jTextFieldname.getText().isEmpty() || jTextFieldpass.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "ID, Name, Address, or Email is missing.");
       } else {
    try {
        // Parse the values from the input fields
        String id = jTextFieldid.getText(); 
        String name = jTextFieldname.getText();  
        String address = jTextFieldaddress.getText(); 
        String pass = jTextFieldpass.getText();  

        // Check if the user ID exists in the database
        String checkQuery = "SELECT COUNT(*) FROM customer WHERE Customer_userID = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setString(1, id);
        ResultSet rs = checkStmt.executeQuery();

        // If the user_ID exists, proceed with the update
        if (rs.next() && rs.getInt(1) > 0) {
            // Prepare the SQL query to update the customer record
            String updateQuery = "UPDATE customer SET Customer_name = ?, Customerpassword = ?, Customer_add = ? WHERE Customer_userID = ?";

            // Prepare the statement and set the parameters
            PreparedStatement updateStmt = Con.prepareStatement(updateQuery);
            updateStmt.setString(1, name);
            updateStmt.setString(2, pass);
            updateStmt.setString(3, address);
            updateStmt.setString(4, id);

            // Execute the update query
            int result = updateStmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Personal details updated successfully.");
                Clear(); // Clear input fields after successful update
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update Personal details.");
            }
        } else {
            // If the user ID doesn't exist, show an error message
            JOptionPane.showMessageDialog(this, "User ID not found in the database.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during database operation: " + e.getMessage());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid input.");
    }
}

    }//GEN-LAST:event_jButtonupdateMouseClicked

    private void jButtonclear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonclear1MouseClicked
        Clear();
    }//GEN-LAST:event_jButtonclear1MouseClicked

     // Method to clear the input fields
    private void Clear() {
        jTextFieldid.setText("");
        jTextFieldname.setText("");
        jTextFieldaddress.setText("");
        jTextFieldpass.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustPersonalInfo().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonclear1;
    private javax.swing.JButton jButtondel;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelimage1;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelid;
    private javax.swing.JTextField jTextFieldaddress;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldpass;
    // End of variables declaration//GEN-END:variables
}
