package Customer;
import bakerymanagementsystem.Login;
import bakerymanagementsystem.SignUp;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hanisha
 */
public class CustDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePersonalInfo
     */
    public CustDashboard() {
        initComponents();
        init();
    }
    
     public void init(){
        setImage();
    }
    
    public void setImage(){
        
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/images/Bakery shop.jpg"));
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/Images/Welcome-11-22-2024 (1).png"));
        
        Image img3 = icon3.getImage().getScaledInstance(jLabelimage3.getWidth(),jLabelimage3.getHeight(),Image.SCALE_SMOOTH);
        Image img4 = icon4.getImage().getScaledInstance(welcome.getWidth(),welcome.getHeight(),Image.SCALE_SMOOTH);
        
        jLabelimage3.setIcon(new ImageIcon(img3));
        welcome.setIcon(new ImageIcon(img4));
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonpersonalinfo = new javax.swing.JButton();
        jButtonordertrack = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonprodbrows = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelimage3 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonpersonalinfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonpersonalinfo.setText("Personal Information ");
        jButtonpersonalinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonpersonalinfoMouseClicked(evt);
            }
        });
        jButtonpersonalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpersonalinfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonpersonalinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 40));

        jButtonordertrack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonordertrack.setText("Order Tracking ");
        jButtonordertrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonordertrackMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonordertrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 280, 40));

        jButton5.setBackground(new java.awt.Color(204, 153, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Log Out");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 90, 30));

        jButtonprodbrows.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonprodbrows.setText("Browsing & Cart ");
        jButtonprodbrows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonprodbrowsMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonprodbrows, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, 40));

        jPanel3.setBackground(new java.awt.Color(204, 153, 0));

        jLabel2.setBackground(new java.awt.Color(187, 143, 110));
        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Homely Treats");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 2));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelimage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery shop.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelimage3)
                    .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelimage3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 710, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonprodbrowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonprodbrowsMouseClicked
        new CartManage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonprodbrowsMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButtonpersonalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpersonalinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonpersonalinfoActionPerformed

    private void jButtonordertrackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonordertrackMouseClicked
        new OrderTracking().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonordertrackMouseClicked

    private void jButtonpersonalinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonpersonalinfoMouseClicked
        new CustPersonalInfo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonpersonalinfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonordertrack;
    private javax.swing.JButton jButtonpersonalinfo;
    private javax.swing.JButton jButtonprodbrows;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelimage3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
