/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanisha
 */
public class OrderTracking extends javax.swing.JFrame {

    public OrderTracking() {
        initComponents();
        setImage();
        Sqlconnector();
    }

    public void setImage(){
       ImageIcon icon1 = new ImageIcon(getClass().getResource("/Images/smart-delivery-tracking-illustration.png"));
       Image img1 = icon1.getImage().getScaledInstance(Pic.getWidth(),Pic.getHeight(),Image.SCALE_SMOOTH);
       Pic.setIcon(new ImageIcon(img1));
       
    }
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;
    
    void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(OrderTracking.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(OrderTracking.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelid = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelname = new javax.swing.JLabel();
        orderid = new javax.swing.JTextField();
        orderdate = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        trackanother = new javax.swing.JButton();
        jButtonnext = new javax.swing.JButton();
        Pic = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ordersearch = new javax.swing.JTextField();
        jButtonsearch = new javax.swing.JButton();
        ordered = new javax.swing.JRadioButton();
        intransit = new javax.swing.JRadioButton();
        cancelled = new javax.swing.JRadioButton();
        out = new javax.swing.JRadioButton();
        delivered = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Track");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 780, 40));

        jPanelid.setBackground(new java.awt.Color(153, 204, 255));
        jPanelid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        jPanelid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Order Date: ");
        jPanelid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 30));

        jLabelemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelemail.setText("Delivery Contact Number:");
        jPanelid.add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabelname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelname.setText("Order ID: ");
        jPanelid.add(jLabelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));
        jPanelid.add(orderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 30));
        jPanelid.add(orderdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 30));
        jPanelid.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 30));

        trackanother.setBackground(new java.awt.Color(0, 102, 255));
        trackanother.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trackanother.setForeground(new java.awt.Color(255, 255, 255));
        trackanother.setText("Track Another Order");
        trackanother.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trackanotherMouseClicked(evt);
            }
        });
        trackanother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackanotherActionPerformed(evt);
            }
        });
        jPanelid.add(trackanother, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 170, 30));

        jButtonnext.setBackground(new java.awt.Color(0, 102, 255));
        jButtonnext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonnext.setForeground(new java.awt.Color(255, 255, 255));
        jButtonnext.setText("Next");
        jButtonnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonnextMouseClicked(evt);
            }
        });
        jButtonnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnextActionPerformed(evt);
            }
        });
        jPanelid.add(jButtonnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 100, 30));
        jPanelid.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 260, 240));

        jPanel1.add(jPanelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 930, 240));

        jButtonback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonbackMouseEntered(evt);
            }
        });
        jPanel1.add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Order ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 80, 30));
        jPanel1.add(ordersearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 270, 30));

        jButtonsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, 30));

        ordered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderedActionPerformed(evt);
            }
        });
        jPanel1.add(ordered, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));
        jPanel1.add(intransit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));
        jPanel1.add(cancelled, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));
        jPanel1.add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));
        jPanel1.add(delivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ordered");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("In Transit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cancelled");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Out for Delivery");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Delivered");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonnextMouseClicked
       new ProductReview().setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_jButtonnextMouseClicked

    private void jButtonbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonbackMouseClicked
        new CustDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonbackMouseClicked

    private void orderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderedActionPerformed

    private void jButtonbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonbackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonbackMouseEntered

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
      String orderId = ordersearch.getText();
      if (orderId.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter an Order ID", "Error", JOptionPane.ERROR_MESSAGE);
    return;
      }
      try {
    // Use the existing database connection (Con is assumed to be already connected)
    String query = "SELECT * FROM orders WHERE OrderID = ?";
    St = Con.prepareStatement(query); // Use the existing connection object
    St.setString(1, orderId); // Set the Order ID in the prepared statement

    // Execute the query
    rst = St.executeQuery();

    if (rst.next()) {
        // Populate the details into the respective text fields
        orderid.setText(rst.getString("OrderID"));
        orderdate.setText(rst.getString("OrderDate"));
        contact.setText(rst.getString("DeliveryPartnerNo"));

        // Set the radio button or status field based on order status
        setRadioButtonStatus(rst.getString("Status"));
    } else {
        // If no matching record is found, show an error message
        JOptionPane.showMessageDialog(this, "Order not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (SQLException e) {
    // Handle SQL exceptions
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error fetching order details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} finally {
    // Close the prepared statement and result set to free up resources
    try {
        if (rst != null) rst.close();
        if (St != null) St.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}

    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jButtonnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnextActionPerformed
       new ProductReview().setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_jButtonnextActionPerformed

    private void trackanotherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackanotherMouseClicked
        Clear();
    }//GEN-LAST:event_trackanotherMouseClicked

    private void trackanotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackanotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackanotherActionPerformed

    
    private void setRadioButtonStatus(String status) {
    if (status == null) return; // Handle null input gracefully

    switch (status.toLowerCase()) {
        case "ordered":
            ordered.setSelected(true);
            intransit.setSelected(false);
            out.setSelected(false);
            delivered.setSelected(false);
            cancelled.setSelected(false);
            break;
        case "in transit":
            ordered.setSelected(false);
            intransit.setSelected(true);
            out.setSelected(false);
            delivered.setSelected(false);
            cancelled.setSelected(false);
            break;
        case "out of delivery":
            ordered.setSelected(false);
            intransit.setSelected(false);
            out.setSelected(true);
            delivered.setSelected(false);
            cancelled.setSelected(false);
            break;
        case "delivered":
            ordered.setSelected(false);
            intransit.setSelected(false);
            delivered.setSelected(true);
            cancelled.setSelected(false);
            out.setSelected(false);
            break;
        case "cancelled":
            cancelled.setSelected(true);
            ordered.setSelected(false);
            intransit.setSelected(false);
            out.setSelected(false);
            delivered.setSelected(false);
            break;
       
    }
}

    
    private void Clear() {
        orderid.setText("");
        orderdate.setText("");
        contact.setText("");
        ordersearch.setText("");
        ordered.setSelected(false);
        intransit.setSelected(false);
        out.setSelected(false);
        delivered.setSelected(false);
        cancelled.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTracking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pic;
    private javax.swing.JRadioButton cancelled;
    private javax.swing.JTextField contact;
    private javax.swing.JRadioButton delivered;
    private javax.swing.JRadioButton intransit;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonnext;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelid;
    private javax.swing.JTextField orderdate;
    private javax.swing.JRadioButton ordered;
    private javax.swing.JTextField orderid;
    private javax.swing.JTextField ordersearch;
    private javax.swing.JRadioButton out;
    private javax.swing.JButton trackanother;
    // End of variables declaration//GEN-END:variables
}
