package Customer;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hanisha
 */
public class ProductReview extends javax.swing.JFrame {
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

    /**
     * Creates new form ProductReview
     */
    public ProductReview() {
        initComponents();
     
        Sqlconnector();
        setImage();
    }
    
    void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(CustPersonalInfo.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(CustPersonalInfo.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
    
   
    
    public void setImage(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/Images/5443569.jpg"));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/Images/star.png"));
        
        Image img1 = icon1.getImage().getScaledInstance(jLabelimage1.getWidth(),jLabelimage1.getHeight(),Image.SCALE_SMOOTH);
        Image img2 = icon2.getImage().getScaledInstance(jLabelimagestar.getWidth(),jLabelimagestar.getHeight(),Image.SCALE_SMOOTH);
        
        jLabelimage1.setIcon(new ImageIcon(img1));
        jLabelimagestar.setIcon(new ImageIcon(img2));
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelproductreview = new javax.swing.JPanel();
        jPanelid = new javax.swing.JPanel();
        jLabelimage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jLabeladdress = new javax.swing.JLabel();
        jTextFieldproductname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldrate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldreview = new javax.swing.JTextField();
        jButtonclear = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jLabelimagestar = new javax.swing.JLabel();
        jLabelback = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelproductreview.setBackground(new java.awt.Color(235, 233, 233));
        jPanelproductreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        jPanelproductreview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelid.setBackground(new java.awt.Color(214, 230, 253));
        jPanelid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        jPanelid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelid.add(jLabelimage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User ID: ");
        jPanelid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));
        jPanelid.add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 210, 30));

        jLabeladdress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabeladdress.setForeground(new java.awt.Color(0, 0, 0));
        jLabeladdress.setText("Product Name: ");
        jPanelid.add(jLabeladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 30));

        jTextFieldproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldproductnameActionPerformed(evt);
            }
        });
        jPanelid.add(jTextFieldproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 210, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rate (1-5): ");
        jPanelid.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, 30));
        jPanelid.add(jTextFieldrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 210, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Review: ");
        jPanelid.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 60, 30));
        jPanelid.add(jTextFieldreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 210, 30));

        jButtonclear.setBackground(new java.awt.Color(0, 102, 255));
        jButtonclear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonclear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonclear.setText("Clear");
        jButtonclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonclearMouseClicked(evt);
            }
        });
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });
        jPanelid.add(jButtonclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 90, 30));

        jButtonsave.setBackground(new java.awt.Color(0, 102, 255));
        jButtonsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsave.setText("Save");
        jButtonsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonsaveMouseEntered(evt);
            }
        });
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });
        jPanelid.add(jButtonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 90, 30));

        jLabelimagestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        jLabelimagestar.setText("star");
        jPanelid.add(jLabelimagestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 30, 30));

        jPanelproductreview.add(jPanelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 750, 420));

        jLabelback.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelback.setForeground(new java.awt.Color(0, 51, 204));
        jLabelback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelback.setText("Product Review");
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });
        jPanelproductreview.add(jLabelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 850, 60));

        jButtonback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonbackMouseClicked(evt);
            }
        });
        jPanelproductreview.add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        getContentPane().add(jPanelproductreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsaveMouseClicked
       // Validate if any required fields are empty
if (jTextFieldid.getText().isEmpty() || jTextFieldproductname.getText().isEmpty() || jTextFieldrate.getText().isEmpty() || jTextFieldreview.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Missing Information");
} else {
    try {
        // Check if Customer_userID exists in the database
        String checkQuery = "SELECT COUNT(*) FROM customer WHERE customer_userID = ?";
        PreparedStatement checkStmt = Con.prepareStatement(checkQuery);
        checkStmt.setString(1, jTextFieldid.getText());
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            // If the user ID exists, proceed to insert the review
            String query = "INSERT INTO productreview (Customer_userID, product_name, rate, review, status) VALUES (?, ?, ?, ?, 'Pending')";
            PreparedStatement addStmt = Con.prepareStatement(query);

            // Set values for the SQL statement
            addStmt.setString(1, jTextFieldid.getText());  // Customer_userID
            addStmt.setString(2, jTextFieldproductname.getText());  // Product name
            addStmt.setInt(3, Integer.parseInt(jTextFieldrate.getText()));  // Rating (convert to int)
            addStmt.setString(4, jTextFieldreview.getText());  // Review

            // Execute the update to insert data
            int row = addStmt.executeUpdate();

            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Review Added Successfully!");
                // Clear fields if needed
                jTextFieldid.setText("");
                jTextFieldproductname.setText("");
                jTextFieldrate.setText("");
                jTextFieldreview.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid User ID. Please enter a valid User ID.");
        }
    } catch (SQLException e) {
        // Handle database connection or query errors
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        e.printStackTrace();
    } catch (NumberFormatException ex) {
        // Handle invalid rating input
        JOptionPane.showMessageDialog(this, "Invalid rating. Please enter a numeric value for the rating.");
    }
}


    }//GEN-LAST:event_jButtonsaveMouseClicked

    private void jButtonclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonclearMouseClicked
        Clear();
    }//GEN-LAST:event_jButtonclearMouseClicked

    private void jButtonbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonbackMouseClicked
        new CustDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonbackMouseClicked

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsaveActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jTextFieldproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldproductnameActionPerformed

    private void jButtonsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsaveMouseEntered

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelbackMouseClicked

    // Method to clear the input fields
    private void Clear() {
        jTextFieldid.setText("");
        jTextFieldproductname.setText("");
        jTextFieldrate.setText("");
        jTextFieldreview.setText("");
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JLabel jLabelimage1;
    private javax.swing.JLabel jLabelimagestar;
    private javax.swing.JPanel jPanelid;
    private javax.swing.JPanel jPanelproductreview;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldproductname;
    private javax.swing.JTextField jTextFieldrate;
    private javax.swing.JTextField jTextFieldreview;
    // End of variables declaration//GEN-END:variables
}
