package Cashier;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import bakerymanagementsystem.Login;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Hanisha
 */
public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage
     */
    public Mainpage() {
        initComponents();
        init();
    }
    
 public void init(){
        setImage();
    }
    
    public void setImage(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/bakerycashier.jpg"));
        
        Image img1 = icon1.getImage().getScaledInstance(jLabelimage.getWidth(),jLabelimage.getHeight(),Image.SCALE_SMOOTH);
        
        jLabelimage.setIcon(new ImageIcon(img1));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jButtonpos = new javax.swing.JButton();
        products = new javax.swing.JButton();
        jButtonreport = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonlogout = new javax.swing.JButton();
        jLabelimage = new javax.swing.JLabel();
        jLabelbakeryname = new javax.swing.JLabel();
        jButtondiscount1 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonpos.setBackground(new java.awt.Color(204, 153, 0));
        jButtonpos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonpos.setText("POS");
        jButtonpos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonposMouseEntered(evt);
            }
        });
        jButtonpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 40));

        products.setBackground(new java.awt.Color(204, 153, 0));
        products.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        products.setText("Products");
        products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMouseClicked(evt);
            }
        });
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        getContentPane().add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 40));

        jButtonreport.setBackground(new java.awt.Color(204, 153, 0));
        jButtonreport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonreport.setText("Report");
        jButtonreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonreportMouseClicked(evt);
            }
        });
        jButtonreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreportActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 200, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, 50));

        jButtonlogout.setBackground(new java.awt.Color(204, 153, 0));
        jButtonlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonlogout.setText("Logout");
        jButtonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonlogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 200, 40));

        jLabelimage.setText("image");
        getContentPane().add(jLabelimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 530));

        jLabelbakeryname.setBackground(new java.awt.Color(153, 102, 0));
        jLabelbakeryname.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabelbakeryname.setText("  Homely Treats ");
        jLabelbakeryname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        getContentPane().add(jLabelbakeryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jButtondiscount1.setBackground(new java.awt.Color(204, 153, 0));
        jButtondiscount1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtondiscount1.setText("Discount");
        jButtondiscount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtondiscount1MouseClicked(evt);
            }
        });
        jButtondiscount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondiscount1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtondiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonposActionPerformed

    }//GEN-LAST:event_jButtonposActionPerformed

    private void jButtonposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonposMouseClicked
        new POS().setVisible(true);  // Open POS page
        this.dispose();  // Close current page
    }//GEN-LAST:event_jButtonposMouseClicked

    private void productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMouseClicked
        new ProductDisplay().setVisible(true);  // Open Discount page
        this.dispose();  // Close current page
    }//GEN-LAST:event_productsMouseClicked

    private void jButtonposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonposMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonposMouseEntered

    private void jButtonreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonreportMouseClicked
        new Reporting().setVisible(true);  // Open Report page
        this.dispose();  // Close current page
    }//GEN-LAST:event_jButtonreportMouseClicked

    private void jButtonreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonreportActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
         new ProductDisplay().setVisible(true);  // Open Discount page
        this.dispose();  // Close current page
    }//GEN-LAST:event_productsActionPerformed

    private void jButtondiscount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtondiscount1MouseClicked
        new ManageDiscount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtondiscount1MouseClicked

    private void jButtondiscount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondiscount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtondiscount1ActionPerformed

    private void jButtonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonlogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();  // Close current page

    }//GEN-LAST:event_jButtonlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mainpage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtondiscount1;
    private javax.swing.JButton jButtonlogout;
    private javax.swing.JButton jButtonpos;
    private javax.swing.JButton jButtonreport;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelbakeryname;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton products;
    // End of variables declaration//GEN-END:variables

}

