/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cashier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hanisha
 */
public class ManageDiscount extends javax.swing.JFrame {
    
    private Connection Con;
    private PreparedStatement St;
    private ResultSet rst;


    /**
     * Creates new form ManageDiscount
     */
    public ManageDiscount() {
        initComponents();
        Sqlconnector();
        loadmanagediscountIntoTable();
    }
    
    void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ManageDiscount.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(ManageDiscount.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproductdisplay = new javax.swing.JTable();
        jLabelcategory = new javax.swing.JLabel();
        jLabelid = new javax.swing.JLabel();
        jLabelname1 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jTextFielddisvalue = new javax.swing.JTextField();
        jButtondelete = new javax.swing.JButton();
        jComboBoxdistype = new javax.swing.JComboBox<>();
        jButtonsave = new javax.swing.JButton();
        jButtonsaveadd = new javax.swing.JButton();
        jButtonsavemodify = new javax.swing.JButton();
        jLabelproductid = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jButtonok2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableproductdisplay.setBackground(new java.awt.Color(204, 204, 204));
        jTableproductdisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Discount Type", "Discount Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableproductdisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproductdisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproductdisplay);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 920, 260));

        jLabelcategory.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabelcategory.setText("Product Name:");
        jPanel2.add(jLabelcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 30));

        jLabelid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelid.setText("Discount Type: ");
        jPanel2.add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabelname1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelname1.setText("Discount Value:");
        jPanel2.add(jLabelname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, 30));

        jTextFieldname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 161, 30));

        jTextFielddisvalue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFielddisvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddisvalueActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFielddisvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 161, 30));

        jButtondelete.setBackground(new java.awt.Color(231, 230, 228));
        jButtondelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtondelete.setText("Delete");
        jButtondelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtondeleteMouseClicked(evt);
            }
        });
        jPanel2.add(jButtondelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 110, 30));

        jComboBoxdistype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxdistype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Percentage", "Amount", " " }));
        jPanel2.add(jComboBoxdistype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 160, 30));

        jButtonsave.setBackground(new java.awt.Color(231, 230, 228));
        jButtonsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsave.setText("Save");
        jButtonsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsaveMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 110, 30));

        jButtonsaveadd.setBackground(new java.awt.Color(231, 230, 228));
        jButtonsaveadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsaveadd.setText("Add");
        jButtonsaveadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsaveaddMouseClicked(evt);
            }
        });
        jButtonsaveadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveaddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonsaveadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 30));

        jButtonsavemodify.setBackground(new java.awt.Color(231, 230, 228));
        jButtonsavemodify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsavemodify.setText("Modify");
        jButtonsavemodify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsavemodifyMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonsavemodify, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 110, 30));

        jLabelproductid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabelproductid.setText("Product ID:");
        jPanel2.add(jLabelproductid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jTextFieldid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 161, 30));

        jButtonok2.setBackground(new java.awt.Color(153, 129, 45));
        jButtonok2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonok2.setText("Back");
        jButtonok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonok2MouseClicked(evt);
            }
        });
        jButtonok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonok2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 980, 540));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Discounts");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielddisvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddisvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddisvalueActionPerformed

    private void jButtondeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtondeleteMouseClicked
       String productId = jTextFieldid.getText();

    if (productId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the Product ID to delete", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Change the table name to 'discounts'
        String query = "DELETE FROM managediscount WHERE product_id = ?";
        St = Con.prepareStatement(query);
        St.setString(1, productId);
        St.executeUpdate();

        JOptionPane.showMessageDialog(this, "Discount deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadmanagediscountIntoTable(); // Refresh the table
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error deleting discount", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtondeleteMouseClicked

    private void jButtonsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsaveMouseClicked
    // Optional: Add additional functionality if needed
    // For example, save modifications or finalize data
    }//GEN-LAST:event_jButtonsaveMouseClicked

    private void jButtonsaveaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsaveaddMouseClicked
  
        // Check if any required fields are empty
        if ( jTextFieldname.getText().isEmpty() || 
    jTextFielddisvalue.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        // Proceed with the insert query
        String query = "INSERT INTO managediscount (product_id, product_name, discount_type, discount_value) VALUES (?, ?, ?, ?)";
        PreparedStatement addStmt = Con.prepareStatement(query);
        
        // Set values for the insert statement
        addStmt.setString(1, jTextFieldid.getText());  // Product ID
        addStmt.setString(2, jTextFieldname.getText());  // Product Name
        addStmt.setString(3, (String) jComboBoxdistype.getSelectedItem());  // Discount Type
        addStmt.setString(4, jTextFielddisvalue.getText());  // Discount Value
        
        // Execute the insert query
        int row = addStmt.executeUpdate();
        
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Discount added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadmanagediscountIntoTable();  // Refresh the table with updated data
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error adding discount: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in Discount Value.");
    }
}

    }//GEN-LAST:event_jButtonsaveaddMouseClicked

    private void jButtonsavemodifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsavemodifyMouseClicked
 // Check if any required fields are empty
if (jTextFieldid.getText().isEmpty() || 
    jTextFieldname.getText().isEmpty() || 
    jTextFielddisvalue.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        // Proceed with the update query (no need to check for product_id as it is expected to be in the database)
        String query = "UPDATE managediscount SET product_name = ?, discount_type = ?, discount_value = ? WHERE product_id = ?";
        St = Con.prepareStatement(query);
        
        // Set values for the update statement
        St.setString(1, jTextFieldname.getText());  // Product Name
        St.setString(2, (String) jComboBoxdistype.getSelectedItem());  // Discount Type
        St.setString(3, jTextFielddisvalue.getText());  // Discount Value (can handle conversion if necessary)
        St.setString(4, jTextFieldid.getText());  // Product ID
        
        // Execute the update query
        int row = St.executeUpdate();
        
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "Discount modified successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadmanagediscountIntoTable();  // Refresh the table with updated data
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error modifying discount: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format in Discount Value.");
    }
}

    }//GEN-LAST:event_jButtonsavemodifyMouseClicked

    
    private void jButtonsaveaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveaddActionPerformed
       
    }//GEN-LAST:event_jButtonsaveaddActionPerformed

    private void jTableproductdisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproductdisplayMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableproductdisplay.getModel();
int selectedIndex = jTableproductdisplay.getSelectedRow();

// Check if a row is selected
if (selectedIndex != -1) {
    // Populate the fields with the selected row data
    jTextFieldid.setText(model.getValueAt(selectedIndex, 0).toString());
    jTextFieldname.setText(model.getValueAt(selectedIndex, 1).toString());
    jComboBoxdistype.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
    jTextFielddisvalue.setText(model.getValueAt(selectedIndex, 3).toString());
} else {
    JOptionPane.showMessageDialog(this, "Please select a row first.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jTableproductdisplayMouseClicked

    private void jButtonok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonok2MouseClicked
        new Mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonok2MouseClicked

    private void jButtonok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonok2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonok2ActionPerformed

     // Load data from the database into the table
        private void loadmanagediscountIntoTable() {
    try {
        
        String query = "SELECT * FROM managediscount"; 
        St = Con.prepareStatement(query);
        rst = St.executeQuery();

        DefaultTableModel d = (DefaultTableModel) jTableproductdisplay.getModel();
        d.setRowCount(0); // Clear existing data

        while (rst.next()) {
            Vector vc = new Vector();
            vc.add(rst.getInt("product_id")); // product_id from 'discounts' table
            vc.add(rst.getString("product_name")); // product_name from 'discounts' table
            vc.add(rst.getString("discount_type")); // discount_type from 'discounts' table
            vc.add(rst.getFloat("discount_value")); // discount_value from 'discounts' table
            d.addRow(vc);
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading discount data: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDiscount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonok2;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JButton jButtonsaveadd;
    private javax.swing.JButton jButtonsavemodify;
    private javax.swing.JComboBox<String> jComboBoxdistype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelcategory;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelname1;
    private javax.swing.JLabel jLabelproductid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableproductdisplay;
    private javax.swing.JTextField jTextFielddisvalue;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    // End of variables declaration//GEN-END:variables
}
