/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cashier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanisha
 */
public class ProductDisplay extends javax.swing.JFrame {
    
    private Connection Con;
    PreparedStatement St;
    ResultSet rst;

    /**
     * Creates new form ProductDisplay
     */
    public ProductDisplay() {
        initComponents();
        Sqlconnector();
        loadproductdisplayIntoTable();
    }

     void  Sqlconnector(){
      try {
       
        Class.forName("com.mysql.cj.jdbc.Driver");
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
          System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ProductDisplay.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(ProductDisplay.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelid = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        jLabelcategory = new javax.swing.JLabel();
        jLabelname1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproductdisplay = new javax.swing.JTable();
        jButtonok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelbakeryname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(139, 87, 39));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product Display");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 670, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelid.setText("ID:");
        jPanel4.add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 161, 36));

        category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breads", "Pastries", "Cakes", "Cookies", "Pie" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel4.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, 38));

        jLabelcategory.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabelcategory.setText("Category:");
        jPanel4.add(jLabelcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabelname1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelname1.setText("Name: ");
        jPanel4.add(jLabelname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 161, 36));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 250, 310));

        jTableproductdisplay.setBackground(new java.awt.Color(204, 204, 204));
        jTableproductdisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Category", "Stock", "Price (RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableproductdisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproductdisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproductdisplay);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 660, 430));

        jButtonok.setBackground(new java.awt.Color(153, 102, 0));
        jButtonok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonok.setText("OK");
        jButtonok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonokMouseClicked(evt);
            }
        });
        jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonokActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonok, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, 540));

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));

        jLabelbakeryname.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabelbakeryname.setText("Homely Treats ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelbakeryname, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelbakeryname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        //jTextField.setText(jComboBox1.getSelectedItem().toString());
        String selectedValue = category.getSelectedItem().toString();
    }//GEN-LAST:event_categoryActionPerformed

    private void jButtonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonokActionPerformed

    private void jButtonokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonokMouseClicked
        new Mainpage().setVisible(true);  // Navigate back to the main page (or another page)
        this.dispose(); // Close the current window
    }//GEN-LAST:event_jButtonokMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jTableproductdisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproductdisplayMouseClicked
      
        DefaultTableModel model = (DefaultTableModel) jTableproductdisplay.getModel();
        int selectedRow = jTableproductdisplay.getSelectedRow();
        if (selectedRow != -1) {
    // Populate fields with the selected row's data
    id.setText(model.getValueAt(selectedRow, 0).toString()); // Product ID
    name.setText(model.getValueAt(selectedRow, 1).toString()); // Product Name
    category.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
} else {
    JOptionPane.showMessageDialog(this, "Please select a product record");
}

    }//GEN-LAST:event_jTableproductdisplayMouseClicked

    private void loadproductdisplayIntoTable() {
    try {
        // SQL query to retrieve all data from the productreview table
        String query = "SELECT * FROM products"; 

        // Prepare the statement and execute the query
        St = Con.prepareStatement(query);
        rst = St.executeQuery();

        // Set up table model
        DefaultTableModel d = (DefaultTableModel) jTableproductdisplay.getModel();
        d.setRowCount(0); // Clear existing data

        // Iterate through result set and populate the table
        while (rst.next()) {
            Vector vc = new Vector();
            vc.add(rst.getInt("product_id"));
            vc.add(rst.getString("product_name"));
            vc.add(rst.getString("category"));
            vc.add(rst.getInt("quantity"));
            vc.add(rst.getDouble("price"));
            d.addRow(vc);
        }

        // Refresh the table
        jTableproductdisplay.repaint();

    } catch (SQLException ex) {
        // Log the exception and show an error message
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading product reviews: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Ensure resources are closed after use
        try {
            if (rst != null) rst.close();
            if (St != null) St.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButtonok;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelbakeryname;
    private javax.swing.JLabel jLabelcategory;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelname1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableproductdisplay;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

}
