/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cashier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanisha
 */
public class Reporting extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    
    /**
     * Creates new form Reporting
     */
    public Reporting() {
        initComponents();
        Sqlconnector();  // Establish database connection
        //loadReportingIntoTable();  
    }
    
     void Sqlconnector() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/homely_treats", "root", "1234");
        System.out.println("Database Connected");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, "Driver not found", ex);
    } catch (SQLException ex) {
        Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, "SQL error", ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelname1 = new javax.swing.JLabel();
        jComboBoxreporttype = new javax.swing.JComboBox<>();
        jButtonsave = new javax.swing.JButton();
        jLabelcategory1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablereport = new javax.swing.JTable();
        jButtonok2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelname1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelname1.setText("Date Range:");
        jPanel2.add(jLabelname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jComboBoxreporttype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxreporttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Performance", "Product Popularity" }));
        jPanel2.add(jComboBoxreporttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 30));

        jButtonsave.setBackground(new java.awt.Color(231, 230, 228));
        jButtonsave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonsave.setText("Ok");
        jButtonsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonsaveMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 110, 30));

        jLabelcategory1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelcategory1.setText("Report Type: ");
        jPanel2.add(jLabelcategory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("From:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("To:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, 30));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 130, 30));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 130, 30));

        jTablereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Quantity Sold", "Total Sales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablereport);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 790, 290));

        jButtonok2.setBackground(new java.awt.Color(153, 129, 45));
        jButtonok2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonok2.setText("Back");
        jButtonok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonok2MouseClicked(evt);
            }
        });
        jButtonok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonok2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 980, 560));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jButtonsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsaveMouseClicked
     
    String reportType = jComboBoxreporttype.getSelectedItem().toString();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String fromDate = (jDateChooser1.getDate() != null) ? sdf.format(jDateChooser1.getDate()) : null;
    String toDate = (jDateChooser2.getDate() != null) ? sdf.format(jDateChooser2.getDate()) : null;

    if (fromDate != null && toDate != null) {
        setTableColumns(reportType); // Set columns dynamically
        loadReportingIntoTable(reportType, fromDate, toDate);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a valid date range.");
    }


    }//GEN-LAST:event_jButtonsaveMouseClicked

    private void jButtonok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonok2MouseClicked
        new Mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonok2MouseClicked

    private void jButtonok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonok2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonok2ActionPerformed

    private void setTableColumns(String reportType) {
    DefaultTableModel model = (DefaultTableModel) jTablereport.getModel();
    if (reportType.equals("Sales Performance")) {
        model.setColumnIdentifiers(new Object[]{"Product ID", "Product Name", "Quantity Sold", "Total Sales"});
    } else if (reportType.equals("Product Popularity")) {
        model.setColumnIdentifiers(new Object[]{"Product ID", "Product Name", "Times Sold"});
    }
}

   private void loadReportingIntoTable(String reportType, String fromDate, String toDate) {
    try {
        String query = "";
        if (reportType.equals("Sales Performance")) {
            query = "SELECT t.product_id, p.product_name, SUM(t.quantity) AS total_quantity, SUM(t.total_price) AS total_sales " +
                    "FROM transactions t " +
                    "JOIN products p ON t.product_id = p.product_id " +
                    "WHERE t.transaction_date BETWEEN ? AND ? " +
                    "GROUP BY t.product_id, p.product_name";
        } else if (reportType.equals("Product Popularity")) {
            query = "SELECT t.product_id, p.product_name, COUNT(t.transaction_id) AS times_sold " +
                    "FROM transactions t " +
                    "JOIN products p ON t.product_id = p.product_id " +
                    "WHERE t.transaction_date BETWEEN ? AND ? " +
                    "GROUP BY t.product_id, p.product_name " +
                    "ORDER BY times_sold DESC";
        }

        // Debugging Logs
        System.out.println("Query: " + query);
        System.out.println("From Date: " + fromDate);
        System.out.println("To Date: " + toDate);

        pst = con.prepareStatement(query);
        pst.setString(1, fromDate + " 00:00:00"); // Include time for DATETIME fields
        pst.setString(2, toDate + " 23:59:59");
        rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTablereport.getModel();
        model.setRowCount(0); // Clear existing rows

        if (!rs.isBeforeFirst()) { // Check if ResultSet is empty
            JOptionPane.showMessageDialog(this, "No data found for the selected date range.");
            return;
        }

        while (rs.next()) {
            if (reportType.equals("Sales Performance")) {
                model.addRow(new Object[]{
                    rs.getString("product_id"),
                    rs.getString("product_name"),
                    rs.getString("total_quantity"),
                    rs.getString("total_sales")
                });
            } else if (reportType.equals("Product Popularity")) {
                model.addRow(new Object[]{
                    rs.getString("product_id"),
                    rs.getString("product_name"),
                    rs.getString("times_sold")
                });
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, null, ex);
    }
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonok2;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JComboBox<String> jComboBoxreporttype;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelcategory1;
    private javax.swing.JLabel jLabelname1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablereport;
    // End of variables declaration//GEN-END:variables
}
